/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  net.minecraft.world.level.block.Block
 *  net.minecraftforge.registries.DeferredRegister
 *  net.minecraftforge.registries.ForgeRegistries
 *  net.minecraftforge.registries.IForgeRegistry
 *  net.minecraftforge.registries.RegistryObject
 */
package rojiuramod.init;

import net.minecraft.world.level.block.Block;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.IForgeRegistry;
import net.minecraftforge.registries.RegistryObject;
import rojiuramod.block.AjisaiBlock;
import rojiuramod.block.AlmDoorBlockBlock;
import rojiuramod.block.AlmWindowBlock;
import rojiuramod.block.AsphaltBlock;
import rojiuramod.block.AsphaltLayerCrackBlock;
import rojiuramod.block.AsphaltLayerDryBlock;
import rojiuramod.block.AsphaltLayerHoleBlock;
import rojiuramod.block.AsphaltLayerLineBlock;
import rojiuramod.block.AsphaltLayerWetBlock;
import rojiuramod.block.AsphaltLayerWhiteBlock;
import rojiuramod.block.AsphaltcrackBlock;
import rojiuramod.block.AsphaltholeBlock;
import rojiuramod.block.AsphaltlineBlock;
import rojiuramod.block.AsphaltwetBlock;
import rojiuramod.block.AsphaltwhiteBlock;
import rojiuramod.block.AwningTentGreenBlock;
import rojiuramod.block.AwningTentRedBlock;
import rojiuramod.block.AwningTentWhiteBlock;
import rojiuramod.block.AwningTentYellowBlock;
import rojiuramod.block.BamBooBlock;
import rojiuramod.block.BarricadeBlock;
import rojiuramod.block.BeachParasolBlueBlock;
import rojiuramod.block.BeachParasolClothBlackBlock;
import rojiuramod.block.BeachParasolClothBrownBlock;
import rojiuramod.block.BeachParasolClothGreenBlock;
import rojiuramod.block.BeachParasolClothWhiteBlock;
import rojiuramod.block.BeachParasolCyanBlock;
import rojiuramod.block.BeachParasolGreenBlock;
import rojiuramod.block.BeachParasolPinkBlock;
import rojiuramod.block.BeachParasolRedBlock;
import rojiuramod.block.BeachParasolStripeCyanBlock;
import rojiuramod.block.BeachParasolStripeGreenBlock;
import rojiuramod.block.BeachParasolStripePinkBlock;
import rojiuramod.block.BeachParasolStripeRed1Block;
import rojiuramod.block.BeachParasolStripeRedBlock;
import rojiuramod.block.BeachParasolStripeYellowBlock;
import rojiuramod.block.BeachParasolYellowBlock;
import rojiuramod.block.BeachRockStairBlock;
import rojiuramod.block.BeachSandBlockBlock;
import rojiuramod.block.BeerBlock;
import rojiuramod.block.BeerCaseBlock;
import rojiuramod.block.BeerCaseRedBlock;
import rojiuramod.block.BenchBlueBlcokBlock;
import rojiuramod.block.BenchRedBlockBlock;
import rojiuramod.block.BenchWoodBlockBlock;
import rojiuramod.block.BollardBlock;
import rojiuramod.block.BuildingMailboxBlock;
import rojiuramod.block.BuoyBlockBlock;
import rojiuramod.block.CansBlockBlock;
import rojiuramod.block.CapselToyMachine2Block;
import rojiuramod.block.CapselToyMachine3Block;
import rojiuramod.block.CapselToyMachine4Block;
import rojiuramod.block.CapselToyMachineBlock;
import rojiuramod.block.CardBoardBedBlock;
import rojiuramod.block.ClothDressBlock;
import rojiuramod.block.CobblestoneBlock;
import rojiuramod.block.CoinBlockBlock;
import rojiuramod.block.ConcreteArchDownBlock;
import rojiuramod.block.ConcreteArchUPBlock;
import rojiuramod.block.ConcreteArchVarticalBlock;
import rojiuramod.block.ConcreteWallBlock;
import rojiuramod.block.ConcreteWallWindholeBlock;
import rojiuramod.block.ConcreteblackBlock;
import rojiuramod.block.ConcreteblueBlock;
import rojiuramod.block.ConcretebrownBlock;
import rojiuramod.block.ConcretecyanBlock;
import rojiuramod.block.ConcretegrayBlock;
import rojiuramod.block.ConcretegreenBlock;
import rojiuramod.block.ConcretelightblueBlock;
import rojiuramod.block.ConcretelimeBlock;
import rojiuramod.block.ConcretemagentaBlock;
import rojiuramod.block.ConcreteorangeBlock;
import rojiuramod.block.ConcretepinkBlock;
import rojiuramod.block.ConcretepurpleBlock;
import rojiuramod.block.ConcreteredBlock;
import rojiuramod.block.ConcretesilverBlock;
import rojiuramod.block.ConcretewhiteBlock;
import rojiuramod.block.ConcreteyellowBlock;
import rojiuramod.block.CoolerBoxBlock;
import rojiuramod.block.CurbBlock;
import rojiuramod.block.DirtyconcreteBlock;
import rojiuramod.block.DoorMetalBlackBlockBlock;
import rojiuramod.block.DoorMetalBrownBlockBlock;
import rojiuramod.block.DoorMetalGreenBlockBlock;
import rojiuramod.block.DoorMetalWhiteBlockBlock;
import rojiuramod.block.DoorMetalYellowBlockBlock;
import rojiuramod.block.DrainPipeBlock;
import rojiuramod.block.DriftwoodBlock;
import rojiuramod.block.DuctBlock;
import rojiuramod.block.ElectricFanBlock;
import rojiuramod.block.ElectricalWireBlock;
import rojiuramod.block.ElectricityMeterBlock;
import rojiuramod.block.EmergencyLightBlock;
import rojiuramod.block.EngawaBlock;
import rojiuramod.block.FanCoverBlock;
import rojiuramod.block.FenderBlock;
import rojiuramod.block.FireExtinguisherBlock;
import rojiuramod.block.FluorescentLightBlock;
import rojiuramod.block.GarbagebasketBlock;
import rojiuramod.block.GasMeterBlock;
import rojiuramod.block.GlassAlmWindowBlock;
import rojiuramod.block.GraffiticoncreteBlock;
import rojiuramod.block.GreenFenceBlock;
import rojiuramod.block.GuardrailWhiteBlock;
import rojiuramod.block.GutunugiIshiBlock;
import rojiuramod.block.HiganbanaBlock;
import rojiuramod.block.HisasiBlock;
import rojiuramod.block.HusumaBlockBlock;
import rojiuramod.block.HusumaBlueLineBlockBlock;
import rojiuramod.block.HusumaInkBlockBlock;
import rojiuramod.block.HusumaSakuraBlockBlock;
import rojiuramod.block.HusumaTallBlockBlock;
import rojiuramod.block.HusumaTallBlueLineBlockBlock;
import rojiuramod.block.HusumaTallInkBlockBlock;
import rojiuramod.block.HusumaTallSakuraBlcokBlock;
import rojiuramod.block.IceCandyBlock;
import rojiuramod.block.IceCandyBoxBlock;
import rojiuramod.block.InsectsBlock;
import rojiuramod.block.ItemTrashBagsBlock;
import rojiuramod.block.JizouBlock;
import rojiuramod.block.KawaraBlackBlockBlock;
import rojiuramod.block.KawaraBlueBlockBlock;
import rojiuramod.block.KawaraGrayBlockBlock;
import rojiuramod.block.KawaraGreenBlockBlock;
import rojiuramod.block.KawaraOddBlackBlockBlock;
import rojiuramod.block.KawaraOddBlueBlockBlock;
import rojiuramod.block.KawaraOddGrayBlockBlock;
import rojiuramod.block.KawaraOddGreenBlockBlock;
import rojiuramod.block.KawaraOddOrangeBlockBlock;
import rojiuramod.block.KawaraOrangeBlockBlock;
import rojiuramod.block.LnvisibleLightBlockBlock;
import rojiuramod.block.LotusPotBlock;
import rojiuramod.block.LowTreeLeafDeepgreenBlock;
import rojiuramod.block.LowTreeLeafLightgreenBlock;
import rojiuramod.block.LpGasCylinderBlock;
import rojiuramod.block.ManholeBlock;
import rojiuramod.block.ManholeClimbingBlock;
import rojiuramod.block.MetalDoorTallBlackBlockBlock;
import rojiuramod.block.MetalDoorTallBrownBlockBlock;
import rojiuramod.block.MetalDoorTallGreenBlockBlock;
import rojiuramod.block.MetalDoorTallWhiteBlockBlock;
import rojiuramod.block.MetalDoorTallWindowBlackBlockBlock;
import rojiuramod.block.MetalDoorTallWindowBrownBlockBlock;
import rojiuramod.block.MetalDoorTallWindowGreenBlockBlock;
import rojiuramod.block.MetalDoorTallWindowWhiteBlockBlock;
import rojiuramod.block.MetalDoorTallWindowYellowBlockBlock;
import rojiuramod.block.MetalDoorTallYellowBlockBlock;
import rojiuramod.block.MetalDoorWindowBlackBlockBlock;
import rojiuramod.block.MetalDoorWindowBrownBlockBlock;
import rojiuramod.block.MetalDoorWindowGreenBlockBlock;
import rojiuramod.block.MetalDoorWindowWhiteBlockBlock;
import rojiuramod.block.MetalDoorWindowYellowBlockBlock;
import rojiuramod.block.MetalFenceBlackBlock;
import rojiuramod.block.MetalFenceBrownBlock;
import rojiuramod.block.MetalFenceGreenBlock;
import rojiuramod.block.MetalFenceWhiteBlock;
import rojiuramod.block.MetalFenceYellowBlock;
import rojiuramod.block.MetalFloorBlackBlock;
import rojiuramod.block.MetalFloorBrownBlock;
import rojiuramod.block.MetalFloorGreenBlock;
import rojiuramod.block.MetalFloorWhiteBlock;
import rojiuramod.block.MetalPillarBlackBlock;
import rojiuramod.block.MetalPillarBlock;
import rojiuramod.block.MetalPillarBrownBlock;
import rojiuramod.block.MetalPillarGreenBlock;
import rojiuramod.block.MetalPillarYellowBlock;
import rojiuramod.block.MetalStairBlackBlock;
import rojiuramod.block.MetalStairBrownBlock;
import rojiuramod.block.MetalStairGreenBlock;
import rojiuramod.block.MetalStairWhiteBlock;
import rojiuramod.block.MetalStairYellowBlock;
import rojiuramod.block.MetalfloorYellowBlock;
import rojiuramod.block.ModernBrickSlabBlock;
import rojiuramod.block.ModernBrickSlabCreamBlock;
import rojiuramod.block.ModernBrickSlabGrayBlock;
import rojiuramod.block.ModernBrickSlabGreenBlock;
import rojiuramod.block.ModernBrickSlabLightBlueBlock;
import rojiuramod.block.ModernBrickSlabOrangeBlock;
import rojiuramod.block.ModernBrickSlabPinkBlock;
import rojiuramod.block.ModernBrickSlabYellowBlock;
import rojiuramod.block.ModernTileBlock;
import rojiuramod.block.ModernTileSlabCreamBlock;
import rojiuramod.block.ModernTileSlabGrayBlock;
import rojiuramod.block.ModernTileSlabGreenBlock;
import rojiuramod.block.ModernTileSlabLightBlueBlock;
import rojiuramod.block.ModernTileSlabOrangeBlock;
import rojiuramod.block.ModernTileSlabPinkBlock;
import rojiuramod.block.ModernTileSlabYellowBlock;
import rojiuramod.block.ModernbrickblueBlock;
import rojiuramod.block.ModernbrickcreamBlock;
import rojiuramod.block.ModernbrickgrayBlock;
import rojiuramod.block.ModernbrickgreenBlock;
import rojiuramod.block.ModernbrickorangeBlock;
import rojiuramod.block.ModernbrickpinkBlock;
import rojiuramod.block.ModernbrickwhiteBlock;
import rojiuramod.block.ModernbrickyellowBlock;
import rojiuramod.block.ModerntileblueBlock;
import rojiuramod.block.ModerntilecreamBlock;
import rojiuramod.block.ModerntilegrayBlock;
import rojiuramod.block.ModerntilegreenBlock;
import rojiuramod.block.ModerntileorangeBlock;
import rojiuramod.block.ModerntilepinkBlock;
import rojiuramod.block.ModerntilewhiteBlock;
import rojiuramod.block.ModerntileyellowBlock;
import rojiuramod.block.MonohosiBarBlock;
import rojiuramod.block.MonohosiBlock;
import rojiuramod.block.MorningGloryBlock;
import rojiuramod.block.MortarCreamSlabBlock;
import rojiuramod.block.MortarGraySlabBlock;
import rojiuramod.block.MortarGreenSlabBlock;
import rojiuramod.block.MortarLightBlueSlabBlock;
import rojiuramod.block.MortarOrangeSlabBlock;
import rojiuramod.block.MortarPinkSlabBlock;
import rojiuramod.block.MortarWhiteSlabBlock;
import rojiuramod.block.MortarYellowSlabBlock;
import rojiuramod.block.MortarcreamBlock;
import rojiuramod.block.MortargrayBlock;
import rojiuramod.block.MortargreenBlock;
import rojiuramod.block.MortarlightblueBlock;
import rojiuramod.block.MortarorangeBlock;
import rojiuramod.block.MortarpinkBlock;
import rojiuramod.block.MortarwhiteBlock;
import rojiuramod.block.MortaryellowBlock;
import rojiuramod.block.MosquitoCoilBlock;
import rojiuramod.block.OldConcreteStairBlock;
import rojiuramod.block.OldDoorBlockBlock;
import rojiuramod.block.OldDoorTallBlockBlock;
import rojiuramod.block.OldPipeBlock;
import rojiuramod.block.OldconcreatBlock;
import rojiuramod.block.OutDoorUnitBlock;
import rojiuramod.block.OutdoorSpotlightBlock;
import rojiuramod.block.PaperLanternBlock;
import rojiuramod.block.ParkBarricadeBlock;
import rojiuramod.block.PicnicSheetBlock;
import rojiuramod.block.PierBlock;
import rojiuramod.block.PierPillarBlock;
import rojiuramod.block.PlyWoodBrownSlabBlock;
import rojiuramod.block.PlyWoodDarkBrownSlabBlock;
import rojiuramod.block.PlyWoodLightBrownSlabBlock;
import rojiuramod.block.PlyWoodOrangeBrownSlabBlock;
import rojiuramod.block.PlyWoodRedSlabBlock;
import rojiuramod.block.PlywoodbrownBlock;
import rojiuramod.block.PlywooddarkbrownBlock;
import rojiuramod.block.PlywoodlightbrownBlock;
import rojiuramod.block.PlywoodorangebrownBlock;
import rojiuramod.block.PlywoodredBlock;
import rojiuramod.block.PostalPostBlock;
import rojiuramod.block.Poster1Block;
import rojiuramod.block.PosterconcreteBlock;
import rojiuramod.block.PublicTelephoneBlock;
import rojiuramod.block.PublicTelephoneTableBlock;
import rojiuramod.block.RanmaBrownBlock;
import rojiuramod.block.RanmaLightBrownBlock;
import rojiuramod.block.RanmaOrangeBrownBlock;
import rojiuramod.block.RecyclingBasketBlock;
import rojiuramod.block.RetainingwallBlock;
import rojiuramod.block.RoadConeBarBlock;
import rojiuramod.block.RoadConeBlock;
import rojiuramod.block.RojiuraNeonBlock;
import rojiuramod.block.RoofSignboardBaseBlock;
import rojiuramod.block.SeaweedBlock;
import rojiuramod.block.SekizouBlock;
import rojiuramod.block.SeppingStoneBlock;
import rojiuramod.block.ShellBlock;
import rojiuramod.block.ShutterCaseBlock;
import rojiuramod.block.ShutterblueBlock;
import rojiuramod.block.ShutterbrownBlock;
import rojiuramod.block.ShuttergrayBlock;
import rojiuramod.block.ShutterwhiteBlock;
import rojiuramod.block.SignBoardWallLBlock;
import rojiuramod.block.SignBoardWallSBlock;
import rojiuramod.block.SitamiItabariBrownSlabBlock;
import rojiuramod.block.SitamiItabariDarkBrownSlabBlock;
import rojiuramod.block.SitamiItabariLightBrownSlabBlock;
import rojiuramod.block.SitamiItabariOrangeBrownSlabBlock;
import rojiuramod.block.SitamiItabariRedSlabBlock;
import rojiuramod.block.SitamiitabaribrownBlock;
import rojiuramod.block.SitamiitabaridarkbrownBlock;
import rojiuramod.block.SitamiitabarilightbrownBlock;
import rojiuramod.block.SitamiitabariorangebrownBlock;
import rojiuramod.block.SitamiitabariredBlock;
import rojiuramod.block.SlidingDoorBrownBlockBlock;
import rojiuramod.block.SlidingDoorLightBrownBlockBlock;
import rojiuramod.block.SlidingDoorOrangeBrownBlockBlock;
import rojiuramod.block.SlidingDoorTallBrownBlockBlock;
import rojiuramod.block.SlidingDoorTallLightBrownBlockBlock;
import rojiuramod.block.SlidingDoorTallOrangeBrownBlockBlock;
import rojiuramod.block.SnailBlock;
import rojiuramod.block.StandingSignBoardBlock;
import rojiuramod.block.StarfishBlock;
import rojiuramod.block.StonewallBlock;
import rojiuramod.block.StreetguttercloseBlock;
import rojiuramod.block.StrongGrassABlock;
import rojiuramod.block.StrongGrassBBlock;
import rojiuramod.block.StuccoBlock;
import rojiuramod.block.StuccowoodbrownBlock;
import rojiuramod.block.StuccowooddarkbrownBlock;
import rojiuramod.block.StuccowoodlightbrownBlock;
import rojiuramod.block.StuccowoodorangebrownBlock;
import rojiuramod.block.StuccowoodredBlock;
import rojiuramod.block.StuucoWoodBrownSlabBlock;
import rojiuramod.block.StuucoWoodDarkSlabBlock;
import rojiuramod.block.StuucoWoodLightBrownSlabBlock;
import rojiuramod.block.StuucoWoodRedSlabBlock;
import rojiuramod.block.StuucoWoodSlabBlock;
import rojiuramod.block.SusukiBlock;
import rojiuramod.block.SyoujiBrownBlockBlock;
import rojiuramod.block.SyoujiLightBrownBlockBlock;
import rojiuramod.block.SyoujiOrangeBrownBlockBlock;
import rojiuramod.block.SyoujiTallBrownBlockBlock;
import rojiuramod.block.SyoujiTallLightBrownBlockBlock;
import rojiuramod.block.SyoujiTallOrangeBrownBlockBlock;
import rojiuramod.block.SyoujiyukimiBrownBlockBlock;
import rojiuramod.block.SyoujiyukimiLightBrownBlockBlock;
import rojiuramod.block.SyoujiyukimiOrangeBrownBlockBlock;
import rojiuramod.block.SyoujiyukimiTallBrownBlockBlock;
import rojiuramod.block.SyoujiyukimiTallLightBrownBlockBlock;
import rojiuramod.block.SyoujiyukimiTallOrangeBrownBlockBlock;
import rojiuramod.block.TatamiGreenBlock;
import rojiuramod.block.TatamiYellwoBlock;
import rojiuramod.block.TotanLSlabBlueBlock;
import rojiuramod.block.TotanLSlabBrownBlock;
import rojiuramod.block.TotanLSlabGrayBlock;
import rojiuramod.block.TotanLSlabGreenBlock;
import rojiuramod.block.TotanLSlabOrangeBlock;
import rojiuramod.block.TotanLSlabPinkBlock;
import rojiuramod.block.TotanLSlabWhiteBlock;
import rojiuramod.block.TotanLSlabYellowBlock;
import rojiuramod.block.TotanRoofBlueBlockBlock;
import rojiuramod.block.TotanRoofGrayBlockBlock;
import rojiuramod.block.TotanRoofRedBlockBlock;
import rojiuramod.block.TotanSSlabBlueBlock;
import rojiuramod.block.TotanSSlabBrownBlock;
import rojiuramod.block.TotanSSlabGrayBlock;
import rojiuramod.block.TotanSSlabGreenBlock;
import rojiuramod.block.TotanSSlabPinkBlock;
import rojiuramod.block.TotanSSlabRedBlock;
import rojiuramod.block.TotanSSlabWhiteBlock;
import rojiuramod.block.TotanSSlabYellowBlock;
import rojiuramod.block.TotanWallBlock;
import rojiuramod.block.TotanlblueBlock;
import rojiuramod.block.TotanlbrownBlock;
import rojiuramod.block.TotanlgrayBlock;
import rojiuramod.block.TotanlgreenBlock;
import rojiuramod.block.TotanlorangeBlock;
import rojiuramod.block.TotanlpinkBlock;
import rojiuramod.block.TotanlwhiteBlock;
import rojiuramod.block.TotanlyellowBlock;
import rojiuramod.block.TotansblueBlock;
import rojiuramod.block.TotansbrownBlock;
import rojiuramod.block.TotansgrayBlock;
import rojiuramod.block.TotansgreenBlock;
import rojiuramod.block.TotanspinkBlock;
import rojiuramod.block.TotansredBlock;
import rojiuramod.block.TotanswhiteBlock;
import rojiuramod.block.TotansyellowBlock;
import rojiuramod.block.TricycleBlock;
import rojiuramod.block.TubakiBlock;
import rojiuramod.block.UnderwearBlock;
import rojiuramod.block.UtilityPoleBottomBlock;
import rojiuramod.block.UtilityPoleLightBlock;
import rojiuramod.block.UtilityPoleMiddleBlock;
import rojiuramod.block.UtilityPolePartBlock;
import rojiuramod.block.UtilityPoleSignsBlock;
import rojiuramod.block.UtilityPoleTopBlock;
import rojiuramod.block.VendingmachineblockBlock;
import rojiuramod.block.WaterHeaterBlock;
import rojiuramod.block.WateringPotBlock;
import rojiuramod.block.WelcomeMatBlock;
import rojiuramod.block.WheelStopBlock;
import rojiuramod.block.WindChimeBlock;
import rojiuramod.block.WoodFloorBarkBrownSlabBlock;
import rojiuramod.block.WoodFloorBlock;
import rojiuramod.block.WoodFloorBrownSlabBlock;
import rojiuramod.block.WoodFloorLightBrownSlabBlock;
import rojiuramod.block.WoodFloorOrangeSlabBlock;
import rojiuramod.block.WoodPillarBrownBlock;
import rojiuramod.block.WoodPillarDarkBlock;
import rojiuramod.block.WoodPillarOrangeBrownBlock;
import rojiuramod.block.WoodPillarRedBlock;
import rojiuramod.block.WoodTobukuroBrown1Block;
import rojiuramod.block.WoodTobukuroBrownBlock;
import rojiuramod.block.WoodTobukuroDarkBlock;
import rojiuramod.block.WoodTobukuroLightBrownBlock;
import rojiuramod.block.WoodTobukuroRedBlock;
import rojiuramod.block.WoodWallBlock;
import rojiuramod.block.WoodWindowBrownBlock;
import rojiuramod.block.WoodWindowDarkBlock;
import rojiuramod.block.WoodWindowLightBrownBlock;
import rojiuramod.block.WoodWindowOrangeBrownBlock;
import rojiuramod.block.WoodWindowRedBlock;
import rojiuramod.block.WoodfloorbrownBlock;
import rojiuramod.block.WoodfloordarkbrownBlock;
import rojiuramod.block.WoodfloorlightbrownBlock;
import rojiuramod.block.WoodfloororangebrownBlock;
import rojiuramod.block.WoodfloorredBlock;
import rojiuramod.block.WoodpillarLightBrownBlock;

public class RojiuramodModBlocks {
    public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create((IForgeRegistry)ForgeRegistries.BLOCKS, (String)"rojiuramod");
    public static final RegistryObject<Block> ASPHALT_DRY = REGISTRY.register("asphalt_dry", () -> new AsphaltBlock());
    public static final RegistryObject<Block> ASPHALT_LINE = REGISTRY.register("asphalt_line", () -> new AsphaltlineBlock());
    public static final RegistryObject<Block> ASPHALT_WHITE = REGISTRY.register("asphalt_white", () -> new AsphaltwhiteBlock());
    public static final RegistryObject<Block> ASPHALT_CRACK = REGISTRY.register("asphalt_crack", () -> new AsphaltcrackBlock());
    public static final RegistryObject<Block> ASPHALT_HOLE = REGISTRY.register("asphalt_hole", () -> new AsphaltholeBlock());
    public static final RegistryObject<Block> ASPHALT_WET = REGISTRY.register("asphalt_wet", () -> new AsphaltwetBlock());
    public static final RegistryObject<Block> COBBLE_STONE = REGISTRY.register("cobble_stone", () -> new CobblestoneBlock());
    public static final RegistryObject<Block> STONE_WALL = REGISTRY.register("stone_wall", () -> new StonewallBlock());
    public static final RegistryObject<Block> POSTER_CONCRETE = REGISTRY.register("poster_concrete", () -> new PosterconcreteBlock());
    public static final RegistryObject<Block> GRAFFITI_CONCRETE = REGISTRY.register("graffiti_concrete", () -> new GraffiticoncreteBlock());
    public static final RegistryObject<Block> DIRTY_CONCRETE = REGISTRY.register("dirty_concrete", () -> new DirtyconcreteBlock());
    public static final RegistryObject<Block> OLD_CONCREAT = REGISTRY.register("old_concreat", () -> new OldconcreatBlock());
    public static final RegistryObject<Block> RETAINING_WALL = REGISTRY.register("retaining_wall", () -> new RetainingwallBlock());
    public static final RegistryObject<Block> STUCCO = REGISTRY.register("stucco", () -> new StuccoBlock());
    public static final RegistryObject<Block> STREET_GUTTER = REGISTRY.register("street_gutter", () -> new StreetguttercloseBlock());
    public static final RegistryObject<Block> WOOD_FLOOR_ORANGE_BROWN = REGISTRY.register("wood_floor_orange_brown", () -> new WoodfloororangebrownBlock());
    public static final RegistryObject<Block> WOOD_FLOOR_LIGHT_BROWN = REGISTRY.register("wood_floor_light_brown", () -> new WoodfloorlightbrownBlock());
    public static final RegistryObject<Block> WOOD_FLOOR_BROWN = REGISTRY.register("wood_floor_brown", () -> new WoodfloorbrownBlock());
    public static final RegistryObject<Block> WOOD_FLOOR_DARK_BROWN = REGISTRY.register("wood_floor_dark_brown", () -> new WoodfloordarkbrownBlock());
    public static final RegistryObject<Block> WOOD_FLOOR_RED = REGISTRY.register("wood_floor_red", () -> new WoodfloorredBlock());
    public static final RegistryObject<Block> PLY_WOOD_ORANGE_BROWN = REGISTRY.register("ply_wood_orange_brown", () -> new PlywoodorangebrownBlock());
    public static final RegistryObject<Block> PLY_WOOD_LIGHT_BROWN = REGISTRY.register("ply_wood_light_brown", () -> new PlywoodlightbrownBlock());
    public static final RegistryObject<Block> PLY_WOOD_BROWN = REGISTRY.register("ply_wood_brown", () -> new PlywoodbrownBlock());
    public static final RegistryObject<Block> PLY_WOOD_DARK_BROWN = REGISTRY.register("ply_wood_dark_brown", () -> new PlywooddarkbrownBlock());
    public static final RegistryObject<Block> PLY_WOOD_RED = REGISTRY.register("ply_wood_red", () -> new PlywoodredBlock());
    public static final RegistryObject<Block> STUCCO_WOOD_ORANGE_BROWN = REGISTRY.register("stucco_wood_orange_brown", () -> new StuccowoodorangebrownBlock());
    public static final RegistryObject<Block> STUCCO_WOOD_LIGHT_BROWN = REGISTRY.register("stucco_wood_light_brown", () -> new StuccowoodlightbrownBlock());
    public static final RegistryObject<Block> STUCCO_WOOD_BROWN = REGISTRY.register("stucco_wood_brown", () -> new StuccowoodbrownBlock());
    public static final RegistryObject<Block> STUCCO_WOOD_DARK_BROWN = REGISTRY.register("stucco_wood_dark_brown", () -> new StuccowooddarkbrownBlock());
    public static final RegistryObject<Block> STUCCO_WOOD_RED = REGISTRY.register("stucco_wood_red", () -> new StuccowoodredBlock());
    public static final RegistryObject<Block> SITAMI_ITABARI_ORANGE_BROWN = REGISTRY.register("sitami_itabari_orange_brown", () -> new SitamiitabariorangebrownBlock());
    public static final RegistryObject<Block> SITAMI_ITABARI_LIGHT_BROWN = REGISTRY.register("sitami_itabari_light_brown", () -> new SitamiitabarilightbrownBlock());
    public static final RegistryObject<Block> SITAMI_ITABARI_BROWN = REGISTRY.register("sitami_itabari_brown", () -> new SitamiitabaribrownBlock());
    public static final RegistryObject<Block> SITAMI_ITABARI_DARK_BROWN = REGISTRY.register("sitami_itabari_dark_brown", () -> new SitamiitabaridarkbrownBlock());
    public static final RegistryObject<Block> SITAMI_ITABARI_RED = REGISTRY.register("sitami_itabari_red", () -> new SitamiitabariredBlock());
    public static final RegistryObject<Block> CONCRETE_RED = REGISTRY.register("concrete_red", () -> new ConcreteredBlock());
    public static final RegistryObject<Block> CONCRETE_MAGENTA = REGISTRY.register("concrete_magenta", () -> new ConcretemagentaBlock());
    public static final RegistryObject<Block> CONCRETE_PINK = REGISTRY.register("concrete_pink", () -> new ConcretepinkBlock());
    public static final RegistryObject<Block> CONCRETE_ORANGE = REGISTRY.register("concrete_orange", () -> new ConcreteorangeBlock());
    public static final RegistryObject<Block> CONCRETE_BROWN = REGISTRY.register("concrete_brown", () -> new ConcretebrownBlock());
    public static final RegistryObject<Block> CONCRETE_YELLOW = REGISTRY.register("concrete_yellow", () -> new ConcreteyellowBlock());
    public static final RegistryObject<Block> CONCRETE_GREEN = REGISTRY.register("concrete_green", () -> new ConcretegreenBlock());
    public static final RegistryObject<Block> CONCRETE_LIME = REGISTRY.register("concrete_lime", () -> new ConcretelimeBlock());
    public static final RegistryObject<Block> CONCRETE_CYAN = REGISTRY.register("concrete_cyan", () -> new ConcretecyanBlock());
    public static final RegistryObject<Block> CONCRETE_LIGHT_BLUE = REGISTRY.register("concrete_light_blue", () -> new ConcretelightblueBlock());
    public static final RegistryObject<Block> CONCRETE_BLUE = REGISTRY.register("concrete_blue", () -> new ConcreteblueBlock());
    public static final RegistryObject<Block> CONCRETE_PURPLE = REGISTRY.register("concrete_purple", () -> new ConcretewhiteBlock());
    public static final RegistryObject<Block> CONCRETE_WHITE = REGISTRY.register("concrete_white", () -> new ConcretesilverBlock());
    public static final RegistryObject<Block> CONCRETE_SILVER = REGISTRY.register("concrete_silver", () -> new ConcretegrayBlock());
    public static final RegistryObject<Block> CONCRETE_GRAY = REGISTRY.register("concrete_gray", () -> new ConcreteblackBlock());
    public static final RegistryObject<Block> CONCRETE_BLACK = REGISTRY.register("concrete_black", () -> new ConcretepurpleBlock());
    public static final RegistryObject<Block> MORTAR_WHITE = REGISTRY.register("mortar_white", () -> new MortarwhiteBlock());
    public static final RegistryObject<Block> MORTAR_CREAM = REGISTRY.register("mortar_cream", () -> new MortarcreamBlock());
    public static final RegistryObject<Block> MORTAR_GRAY = REGISTRY.register("mortar_gray", () -> new MortargrayBlock());
    public static final RegistryObject<Block> MORTAR_YELLOW = REGISTRY.register("mortar_yellow", () -> new MortaryellowBlock());
    public static final RegistryObject<Block> MORTAR_ORANGE = REGISTRY.register("mortar_orange", () -> new MortarorangeBlock());
    public static final RegistryObject<Block> MORTAR_PINK = REGISTRY.register("mortar_pink", () -> new MortarpinkBlock());
    public static final RegistryObject<Block> MORTAR_GREEN = REGISTRY.register("mortar_green", () -> new MortargreenBlock());
    public static final RegistryObject<Block> MORTAR_LIGHT_BLUE = REGISTRY.register("mortar_light_blue", () -> new MortarlightblueBlock());
    public static final RegistryObject<Block> MODERN_BRICK_WHITE = REGISTRY.register("modern_brick_white", () -> new ModernbrickwhiteBlock());
    public static final RegistryObject<Block> MODERN_BRICK_YELLOW = REGISTRY.register("modern_brick_yellow", () -> new ModernbrickyellowBlock());
    public static final RegistryObject<Block> MODERN_BRICK_ORANGE = REGISTRY.register("modern_brick_orange", () -> new ModernbrickorangeBlock());
    public static final RegistryObject<Block> MODERN_BRICK_BLUE = REGISTRY.register("modern_brick_blue", () -> new ModernbrickblueBlock());
    public static final RegistryObject<Block> MODERN_BRICK_GRAY = REGISTRY.register("modern_brick_gray", () -> new ModernbrickgrayBlock());
    public static final RegistryObject<Block> MODERN_BRICK_PINK = REGISTRY.register("modern_brick_pink", () -> new ModernbrickpinkBlock());
    public static final RegistryObject<Block> MODERN_BRICK_GREEN = REGISTRY.register("modern_brick_green", () -> new ModernbrickgreenBlock());
    public static final RegistryObject<Block> MODERN_BRICK_CREAM = REGISTRY.register("modern_brick_cream", () -> new ModernbrickcreamBlock());
    public static final RegistryObject<Block> MODERN_TILE_WHITE = REGISTRY.register("modern_tile_white", () -> new ModerntilewhiteBlock());
    public static final RegistryObject<Block> MODERN_TILE_YELLOW = REGISTRY.register("modern_tile_yellow", () -> new ModerntileyellowBlock());
    public static final RegistryObject<Block> MODERN_TILE_ORANGE = REGISTRY.register("modern_tile_orange", () -> new ModerntileorangeBlock());
    public static final RegistryObject<Block> MODERN_TILE_GREEN = REGISTRY.register("modern_tile_green", () -> new ModerntilegreenBlock());
    public static final RegistryObject<Block> MODERN_TILE_BLUE = REGISTRY.register("modern_tile_blue", () -> new ModerntileblueBlock());
    public static final RegistryObject<Block> MODERN_TILE_GRAY = REGISTRY.register("modern_tile_gray", () -> new ModerntilegrayBlock());
    public static final RegistryObject<Block> MODERN_TILE_PINK = REGISTRY.register("modern_tile_pink", () -> new ModerntilepinkBlock());
    public static final RegistryObject<Block> MODERN_TILE_CREAM = REGISTRY.register("modern_tile_cream", () -> new ModerntilecreamBlock());
    public static final RegistryObject<Block> TOTAN_S_BLUE = REGISTRY.register("totan_s_blue", () -> new TotansblueBlock());
    public static final RegistryObject<Block> TOTAN_S_WHITE = REGISTRY.register("totan_s_white", () -> new TotanswhiteBlock());
    public static final RegistryObject<Block> TOTAN_S_PINK = REGISTRY.register("totan_s_pink", () -> new TotanspinkBlock());
    public static final RegistryObject<Block> TOTAN_S_YELLOW = REGISTRY.register("totan_s_yellow", () -> new TotansyellowBlock());
    public static final RegistryObject<Block> TOTAN_S_BROWN = REGISTRY.register("totan_s_brown", () -> new TotansbrownBlock());
    public static final RegistryObject<Block> TOTAN_S_GRAY = REGISTRY.register("totan_s_gray", () -> new TotansgrayBlock());
    public static final RegistryObject<Block> TOTAN_S_GREEN = REGISTRY.register("totan_s_green", () -> new TotansgreenBlock());
    public static final RegistryObject<Block> TOTAN_S_RED = REGISTRY.register("totan_s_red", () -> new TotansredBlock());
    public static final RegistryObject<Block> TOTAN_L_BLUE = REGISTRY.register("totan_l_blue", () -> new TotanlblueBlock());
    public static final RegistryObject<Block> TOTAN_L_WHITE = REGISTRY.register("totan_l_white", () -> new TotanlwhiteBlock());
    public static final RegistryObject<Block> TOTAN_L_PINK = REGISTRY.register("totan_l_pink", () -> new TotanlpinkBlock());
    public static final RegistryObject<Block> TOTAN_L_YELLOW = REGISTRY.register("totan_l_yellow", () -> new TotanlyellowBlock());
    public static final RegistryObject<Block> TOTAN_L_BROWN = REGISTRY.register("totan_l_brown", () -> new TotanlbrownBlock());
    public static final RegistryObject<Block> TOTAN_L_GRAY = REGISTRY.register("totan_l_gray", () -> new TotanlgrayBlock());
    public static final RegistryObject<Block> TOTAN_L_GREEN = REGISTRY.register("totan_l_green", () -> new TotanlgreenBlock());
    public static final RegistryObject<Block> TOTAN_L_ORANGE = REGISTRY.register("totan_l_orange", () -> new TotanlorangeBlock());
    public static final RegistryObject<Block> SHUTTER_WHITE = REGISTRY.register("shutter_white", () -> new ShutterwhiteBlock());
    public static final RegistryObject<Block> SHUTTER_BLUE = REGISTRY.register("shutter_blue", () -> new ShutterblueBlock());
    public static final RegistryObject<Block> SHUTTER_BROWN = REGISTRY.register("shutter_brown", () -> new ShutterbrownBlock());
    public static final RegistryObject<Block> SHUTTER_GRAY = REGISTRY.register("shutter_gray", () -> new ShuttergrayBlock());
    public static final RegistryObject<Block> PAPER_LANTERN = REGISTRY.register("paper_lantern", () -> new PaperLanternBlock());
    public static final RegistryObject<Block> GARBAGE_BASKET = REGISTRY.register("garbage_basket", () -> new GarbagebasketBlock());
    public static final RegistryObject<Block> WATERING_POT = REGISTRY.register("watering_pot", () -> new WateringPotBlock());
    public static final RegistryObject<Block> MORNING_GLORY = REGISTRY.register("morning_glory", () -> new MorningGloryBlock());
    public static final RegistryObject<Block> MANHOLE = REGISTRY.register("manhole", () -> new ManholeBlock());
    public static final RegistryObject<Block> BEER_CASE = REGISTRY.register("beer_case", () -> new BeerCaseBlock());
    public static final RegistryObject<Block> BEER_BLOCK = REGISTRY.register("beer_block", () -> new BeerBlock());
    public static final RegistryObject<Block> BEER_CASE_RED = REGISTRY.register("beer_case_red", () -> new BeerCaseRedBlock());
    public static final RegistryObject<Block> STRONG_GRASS_A = REGISTRY.register("strong_grass_a", () -> new StrongGrassABlock());
    public static final RegistryObject<Block> STRONG_GRASS_B = REGISTRY.register("strong_grass_b", () -> new StrongGrassBBlock());
    public static final RegistryObject<Block> EMERGENCY_LIGHT = REGISTRY.register("emergency_light", () -> new EmergencyLightBlock());
    public static final RegistryObject<Block> FLUORESCENT_LIGHT = REGISTRY.register("fluorescent_light", () -> new FluorescentLightBlock());
    public static final RegistryObject<Block> ICE_CANDY_BOX = REGISTRY.register("ice_candy_box", () -> new IceCandyBoxBlock());
    public static final RegistryObject<Block> RECYCLING_BASKET = REGISTRY.register("recycling_basket", () -> new RecyclingBasketBlock());
    public static final RegistryObject<Block> TRICYCLE = REGISTRY.register("tricycle", () -> new TricycleBlock());
    public static final RegistryObject<Block> POSTAL_POST = REGISTRY.register("postal_post", () -> new PostalPostBlock());
    public static final RegistryObject<Block> BEACH_PARASOL_BLUE = REGISTRY.register("beach_parasol_blue", () -> new BeachParasolBlueBlock());
    public static final RegistryObject<Block> LOTUS_POT = REGISTRY.register("lotus_pot", () -> new LotusPotBlock());
    public static final RegistryObject<Block> FIRE_EXTINGUISHER = REGISTRY.register("fire_extinguisher", () -> new FireExtinguisherBlock());
    public static final RegistryObject<Block> WELCOME_MAT = REGISTRY.register("welcome_mat", () -> new WelcomeMatBlock());
    public static final RegistryObject<Block> SEPPING_STONE = REGISTRY.register("sepping_stone", () -> new SeppingStoneBlock());
    public static final RegistryObject<Block> ROJIURA_NEON = REGISTRY.register("rojiura_neon", () -> new RojiuraNeonBlock());
    public static final RegistryObject<Block> STANDING_SIGN_BOARD = REGISTRY.register("standing_sign_board", () -> new StandingSignBoardBlock());
    public static final RegistryObject<Block> SIGN_BOARD_WALL_S = REGISTRY.register("sign_board_wall_s", () -> new SignBoardWallSBlock());
    public static final RegistryObject<Block> SIGN_BOARD_WALL_L = REGISTRY.register("sign_board_wall_l", () -> new SignBoardWallLBlock());
    public static final RegistryObject<Block> INSECTS = REGISTRY.register("insects", () -> new InsectsBlock());
    public static final RegistryObject<Block> AWNING_TENT_GREEN = REGISTRY.register("awning_tent_green", () -> new AwningTentGreenBlock());
    public static final RegistryObject<Block> AWNING_TENT_RED = REGISTRY.register("awning_tent_red", () -> new AwningTentRedBlock());
    public static final RegistryObject<Block> AWNING_TENT_WHITE = REGISTRY.register("awning_tent_white", () -> new AwningTentWhiteBlock());
    public static final RegistryObject<Block> AWNING_TENT_YELLOW = REGISTRY.register("awning_tent_yellow", () -> new AwningTentYellowBlock());
    public static final RegistryObject<Block> ASPHALT_LAYER_DRY_BLOCK = REGISTRY.register("asphalt_layer_dry_block", () -> new AsphaltLayerDryBlock());
    public static final RegistryObject<Block> ASPHALT_LAYER_LINE_BLOCK = REGISTRY.register("asphalt_layer_line_block", () -> new AsphaltLayerLineBlock());
    public static final RegistryObject<Block> ASPHALT_LAYER_WHITE_BLOCK = REGISTRY.register("asphalt_layer_white_block", () -> new AsphaltLayerWhiteBlock());
    public static final RegistryObject<Block> ASPHALT_LAYER_CRACK_BLOCK = REGISTRY.register("asphalt_layer_crack_block", () -> new AsphaltLayerCrackBlock());
    public static final RegistryObject<Block> ASPHALT_LAYER_HOLE_BLOCK = REGISTRY.register("asphalt_layer_hole_block", () -> new AsphaltLayerHoleBlock());
    public static final RegistryObject<Block> ASPHALT_LAYER_WET_BLOCK = REGISTRY.register("asphalt_layer_wet_block", () -> new AsphaltLayerWetBlock());
    public static final RegistryObject<Block> MANHOLE_CLIMBING = REGISTRY.register("manhole_climbing", () -> new ManholeClimbingBlock());
    public static final RegistryObject<Block> CONCRETE_ARCH_UP = REGISTRY.register("concrete_arch_up", () -> new ConcreteArchUPBlock());
    public static final RegistryObject<Block> CONCRETE_ARCH_DOWN = REGISTRY.register("concrete_arch_down", () -> new ConcreteArchDownBlock());
    public static final RegistryObject<Block> CONCRETE_ARCH_VARTICAL = REGISTRY.register("concrete_arch_vartical", () -> new ConcreteArchVarticalBlock());
    public static final RegistryObject<Block> WOOD_FLOOR_RED_SLAB = REGISTRY.register("wood_floor_red_slab", () -> new WoodFloorBlock());
    public static final RegistryObject<Block> WOOD_FLOOR_ORANGE_BROWN_SLAB = REGISTRY.register("wood_floor_orange_brown_slab", () -> new WoodFloorOrangeSlabBlock());
    public static final RegistryObject<Block> WOOD_FLOOR_LIGHT_BROWN_SLAB = REGISTRY.register("wood_floor_light_brown_slab", () -> new WoodFloorLightBrownSlabBlock());
    public static final RegistryObject<Block> WOOD_FLOOR_BROWN_SLAB = REGISTRY.register("wood_floor_brown_slab", () -> new WoodFloorBrownSlabBlock());
    public static final RegistryObject<Block> WOOD_FLOOR_DARK_BROWN_SLAB = REGISTRY.register("wood_floor_dark_brown_slab", () -> new WoodFloorBarkBrownSlabBlock());
    public static final RegistryObject<Block> PLY_WOOD_ORANGE_BROWN_SLAB = REGISTRY.register("ply_wood_orange_brown_slab", () -> new PlyWoodOrangeBrownSlabBlock());
    public static final RegistryObject<Block> PLY_WOOD_LIGHT_BROWN_SLAB = REGISTRY.register("ply_wood_light_brown_slab", () -> new PlyWoodLightBrownSlabBlock());
    public static final RegistryObject<Block> PLY_WOOD_BROWN_SLAB = REGISTRY.register("ply_wood_brown_slab", () -> new PlyWoodBrownSlabBlock());
    public static final RegistryObject<Block> PLY_WOOD_DARK_BROWN_SLAB = REGISTRY.register("ply_wood_dark_brown_slab", () -> new PlyWoodDarkBrownSlabBlock());
    public static final RegistryObject<Block> PLY_WOOD_RED_SLAB = REGISTRY.register("ply_wood_red_slab", () -> new PlyWoodRedSlabBlock());
    public static final RegistryObject<Block> STUUCO_WOOD_ORANGE_BROWN_SLAB = REGISTRY.register("stuuco_wood_orange_brown_slab", () -> new StuucoWoodSlabBlock());
    public static final RegistryObject<Block> STUUCO_WOOD_LIGHT_BROWN_SLAB = REGISTRY.register("stuuco_wood_light_brown_slab", () -> new StuucoWoodLightBrownSlabBlock());
    public static final RegistryObject<Block> STUUCO_WOOD_BROWN_SLAB = REGISTRY.register("stuuco_wood_brown_slab", () -> new StuucoWoodBrownSlabBlock());
    public static final RegistryObject<Block> STUUCO_WOOD_DARK_SLAB = REGISTRY.register("stuuco_wood_dark_slab", () -> new StuucoWoodDarkSlabBlock());
    public static final RegistryObject<Block> STUUCO_WOOD_RED_SLAB = REGISTRY.register("stuuco_wood_red_slab", () -> new StuucoWoodRedSlabBlock());
    public static final RegistryObject<Block> TATAMI_YELLWO_BLOCK = REGISTRY.register("tatami_yellwo_block", () -> new TatamiYellwoBlock());
    public static final RegistryObject<Block> TATAMI_GREEN_BLOCK = REGISTRY.register("tatami_green_block", () -> new TatamiGreenBlock());
    public static final RegistryObject<Block> MORTAR_WHITE_SLAB = REGISTRY.register("mortar_white_slab", () -> new MortarWhiteSlabBlock());
    public static final RegistryObject<Block> MORTAR_YELLOW_SLAB = REGISTRY.register("mortar_yellow_slab", () -> new MortarYellowSlabBlock());
    public static final RegistryObject<Block> MORTAR_ORANGE_SLAB = REGISTRY.register("mortar_orange_slab", () -> new MortarOrangeSlabBlock());
    public static final RegistryObject<Block> MORTAR_LIGHT_BLUE_SLAB = REGISTRY.register("mortar_light_blue_slab", () -> new MortarLightBlueSlabBlock());
    public static final RegistryObject<Block> MORTAR_GRAY_SLAB = REGISTRY.register("mortar_gray_slab", () -> new MortarGraySlabBlock());
    public static final RegistryObject<Block> MORTAR_GREEN_SLAB = REGISTRY.register("mortar_green_slab", () -> new MortarGreenSlabBlock());
    public static final RegistryObject<Block> MORTAR_CREAM_SLAB = REGISTRY.register("mortar_cream_slab", () -> new MortarCreamSlabBlock());
    public static final RegistryObject<Block> MODERN_BRICK_WHITE_SLAB = REGISTRY.register("modern_brick_white_slab", () -> new ModernBrickSlabBlock());
    public static final RegistryObject<Block> MODERN_BRICK_YELLOW_SLAB = REGISTRY.register("modern_brick_yellow_slab", () -> new ModernBrickSlabYellowBlock());
    public static final RegistryObject<Block> MODERN_BRICK_GREEN_SLAB = REGISTRY.register("modern_brick_green_slab", () -> new ModernBrickSlabGreenBlock());
    public static final RegistryObject<Block> MODERN_BRICK_ORANGE_SLAB = REGISTRY.register("modern_brick_orange_slab", () -> new ModernBrickSlabOrangeBlock());
    public static final RegistryObject<Block> MODERN_BRICK_BLUE_SLAB = REGISTRY.register("modern_brick_blue_slab", () -> new ModernBrickSlabLightBlueBlock());
    public static final RegistryObject<Block> MODERN_BRICK_GRAY_SLAB = REGISTRY.register("modern_brick_gray_slab", () -> new ModernBrickSlabGrayBlock());
    public static final RegistryObject<Block> MODERN_BRICK_PINK_SLAB = REGISTRY.register("modern_brick_pink_slab", () -> new ModernBrickSlabPinkBlock());
    public static final RegistryObject<Block> MODERN_BRICK_CREAM_SLAB = REGISTRY.register("modern_brick_cream_slab", () -> new ModernBrickSlabCreamBlock());
    public static final RegistryObject<Block> MODERN_TILE_WHITE_SLAB = REGISTRY.register("modern_tile_white_slab", () -> new ModernTileBlock());
    public static final RegistryObject<Block> MODERN_TILE_YELLOW_SLAB = REGISTRY.register("modern_tile_yellow_slab", () -> new ModernTileSlabYellowBlock());
    public static final RegistryObject<Block> MODERN_TILE_ORANGE_SLAB = REGISTRY.register("modern_tile_orange_slab", () -> new ModernTileSlabOrangeBlock());
    public static final RegistryObject<Block> MODERN_TILE_BLUE_SLAB = REGISTRY.register("modern_tile_blue_slab", () -> new ModernTileSlabLightBlueBlock());
    public static final RegistryObject<Block> MODERN_TILE_GRAY_SLAB = REGISTRY.register("modern_tile_gray_slab", () -> new ModernTileSlabGrayBlock());
    public static final RegistryObject<Block> MODERN_TILE_PINK_SLAB = REGISTRY.register("modern_tile_pink_slab", () -> new ModernTileSlabPinkBlock());
    public static final RegistryObject<Block> MODERN_TILE_GREEN_SLAB = REGISTRY.register("modern_tile_green_slab", () -> new ModernTileSlabGreenBlock());
    public static final RegistryObject<Block> MODERN_TILE_CREAM_SLAB = REGISTRY.register("modern_tile_cream_slab", () -> new ModernTileSlabCreamBlock());
    public static final RegistryObject<Block> TOTAN_S_BLUE_SLAB = REGISTRY.register("totan_s_blue_slab", () -> new TotanSSlabBlueBlock());
    public static final RegistryObject<Block> TOTAN_S_WHITE_SLAB = REGISTRY.register("totan_s_white_slab", () -> new TotanSSlabWhiteBlock());
    public static final RegistryObject<Block> TOTAN_S_PINK_SLAB = REGISTRY.register("totan_s_pink_slab", () -> new TotanSSlabPinkBlock());
    public static final RegistryObject<Block> TOTAN_S_YELLOW_SLAB = REGISTRY.register("totan_s_yellow_slab", () -> new TotanSSlabYellowBlock());
    public static final RegistryObject<Block> TOTAN_S_BROWN_SLAB = REGISTRY.register("totan_s_brown_slab", () -> new TotanSSlabBrownBlock());
    public static final RegistryObject<Block> TOTAN_S_GRAY_SLAB = REGISTRY.register("totan_s_gray_slab", () -> new TotanSSlabGrayBlock());
    public static final RegistryObject<Block> TOTAN_S_GREEN_SLAB = REGISTRY.register("totan_s_green_slab", () -> new TotanSSlabGreenBlock());
    public static final RegistryObject<Block> TOTAN_S_RED_SLAB = REGISTRY.register("totan_s_red_slab", () -> new TotanSSlabRedBlock());
    public static final RegistryObject<Block> TOTAN_L_BLUE_SLAB = REGISTRY.register("totan_l_blue_slab", () -> new TotanLSlabBlueBlock());
    public static final RegistryObject<Block> TOTAN_L_WHITE_SLAB = REGISTRY.register("totan_l_white_slab", () -> new TotanLSlabWhiteBlock());
    public static final RegistryObject<Block> TOTAN_L_PINK_SLAB = REGISTRY.register("totan_l_pink_slab", () -> new TotanLSlabPinkBlock());
    public static final RegistryObject<Block> TOTAN_L_YELLOW_SLAB = REGISTRY.register("totan_l_yellow_slab", () -> new TotanLSlabYellowBlock());
    public static final RegistryObject<Block> TOTAN_L_BROWN_SLAB = REGISTRY.register("totan_l_brown_slab", () -> new TotanLSlabBrownBlock());
    public static final RegistryObject<Block> TOTAN_L_GRAY_SLAB = REGISTRY.register("totan_l_gray_slab", () -> new TotanLSlabGrayBlock());
    public static final RegistryObject<Block> TOTAN_L_GREEN_SLAB = REGISTRY.register("totan_l_green_slab", () -> new TotanLSlabGreenBlock());
    public static final RegistryObject<Block> TOTAN_L_ORANGE_SLAB = REGISTRY.register("totan_l_orange_slab", () -> new TotanLSlabOrangeBlock());
    public static final RegistryObject<Block> MORTAR_PINK_SLAB = REGISTRY.register("mortar_pink_slab", () -> new MortarPinkSlabBlock());
    public static final RegistryObject<Block> KUTUNUGI_ISHI = REGISTRY.register("kutunugi_ishi", () -> new GutunugiIshiBlock());
    public static final RegistryObject<Block> WIND_CHIME = REGISTRY.register("wind_chime", () -> new WindChimeBlock());
    public static final RegistryObject<Block> MOSQUITO_COIL = REGISTRY.register("mosquito_coil", () -> new MosquitoCoilBlock());
    public static final RegistryObject<Block> LOW_TREE_LEAF_LIGHTGREEN = REGISTRY.register("low_tree_leaf_lightgreen", () -> new LowTreeLeafLightgreenBlock());
    public static final RegistryObject<Block> LOW_TREE_LEAF_DEEPGREEN = REGISTRY.register("low_tree_leaf_deepgreen", () -> new LowTreeLeafDeepgreenBlock());
    public static final RegistryObject<Block> BAM_BOO = REGISTRY.register("bam_boo", () -> new BamBooBlock());
    public static final RegistryObject<Block> AJISAI = REGISTRY.register("ajisai", () -> new AjisaiBlock());
    public static final RegistryObject<Block> HIGANBANA = REGISTRY.register("higanbana", () -> new HiganbanaBlock());
    public static final RegistryObject<Block> SUSUKI = REGISTRY.register("susuki", () -> new SusukiBlock());
    public static final RegistryObject<Block> TUBAKI = REGISTRY.register("tubaki", () -> new TubakiBlock());
    public static final RegistryObject<Block> CAPSEL_TOY_MACHINE = REGISTRY.register("capsel_toy_machine", () -> new CapselToyMachineBlock());
    public static final RegistryObject<Block> CAPSEL_TOY_MACHINE_2 = REGISTRY.register("capsel_toy_machine_2", () -> new CapselToyMachine2Block());
    public static final RegistryObject<Block> CAPSEL_TOY_MACHINE_3 = REGISTRY.register("capsel_toy_machine_3", () -> new CapselToyMachine3Block());
    public static final RegistryObject<Block> CAPSEL_TOY_MACHINE_4 = REGISTRY.register("capsel_toy_machine_4", () -> new CapselToyMachine4Block());
    public static final RegistryObject<Block> BARRICADE = REGISTRY.register("barricade", () -> new BarricadeBlock());
    public static final RegistryObject<Block> PARK_BARRICADE = REGISTRY.register("park_barricade", () -> new ParkBarricadeBlock());
    public static final RegistryObject<Block> ROAD_CONE = REGISTRY.register("road_cone", () -> new RoadConeBlock());
    public static final RegistryObject<Block> ROAD_CONE_BAR = REGISTRY.register("road_cone_bar", () -> new RoadConeBarBlock());
    public static final RegistryObject<Block> PUBLIC_TELEPHONE = REGISTRY.register("public_telephone", () -> new PublicTelephoneBlock());
    public static final RegistryObject<Block> PUBLIC_TELEPHONE_TABLE = REGISTRY.register("public_telephone_table", () -> new PublicTelephoneTableBlock());
    public static final RegistryObject<Block> ELECTRIC_FAN = REGISTRY.register("electric_fan", () -> new ElectricFanBlock());
    public static final RegistryObject<Block> JIZOU = REGISTRY.register("jizou", () -> new JizouBlock());
    public static final RegistryObject<Block> SEKIZOU = REGISTRY.register("sekizou", () -> new SekizouBlock());
    public static final RegistryObject<Block> ICE_CANDY_BLOCK = REGISTRY.register("ice_candy_block", () -> new IceCandyBlock());
    public static final RegistryObject<Block> ITEM_TRASH_BAGS = REGISTRY.register("item_trash_bags", () -> new ItemTrashBagsBlock());
    public static final RegistryObject<Block> CARD_BOARD_BED_BLOCK = REGISTRY.register("card_board_bed_block", () -> new CardBoardBedBlock());
    public static final RegistryObject<Block> VENDINGMACHINEBLOCK = REGISTRY.register("vendingmachineblock", () -> new VendingmachineblockBlock());
    public static final RegistryObject<Block> BENCH_BLUE_BLCOK = REGISTRY.register("bench_blue_blcok", () -> new BenchBlueBlcokBlock());
    public static final RegistryObject<Block> BENCH_RED_BLOCK = REGISTRY.register("bench_red_block", () -> new BenchRedBlockBlock());
    public static final RegistryObject<Block> BENCH_WOOD_BLOCK = REGISTRY.register("bench_wood_block", () -> new BenchWoodBlockBlock());
    public static final RegistryObject<Block> CANS_BLOCK = REGISTRY.register("cans_block", () -> new CansBlockBlock());
    public static final RegistryObject<Block> INVISIBLE_LIGHT_BLOCK = REGISTRY.register("invisible_light_block", () -> new LnvisibleLightBlockBlock());
    public static final RegistryObject<Block> COIN_BLOCK = REGISTRY.register("coin_block", () -> new CoinBlockBlock());
    public static final RegistryObject<Block> OUT_DOOR_UNIT = REGISTRY.register("out_door_unit", () -> new OutDoorUnitBlock());
    public static final RegistryObject<Block> BEACH_ROCK_STAIR = REGISTRY.register("beach_rock_stair", () -> new BeachRockStairBlock());
    public static final RegistryObject<Block> POSTERS = REGISTRY.register("posters", () -> new Poster1Block());
    public static final RegistryObject<Block> BEACH_PARASOL_RED = REGISTRY.register("beach_parasol_red", () -> new BeachParasolRedBlock());
    public static final RegistryObject<Block> BEACH_PARASOL_CYAN = REGISTRY.register("beach_parasol_cyan", () -> new BeachParasolCyanBlock());
    public static final RegistryObject<Block> BEACH_PARASOL_YELLOW = REGISTRY.register("beach_parasol_yellow", () -> new BeachParasolYellowBlock());
    public static final RegistryObject<Block> BEACH_PARASOL_PINK = REGISTRY.register("beach_parasol_pink", () -> new BeachParasolPinkBlock());
    public static final RegistryObject<Block> BEACH_PARASOL_GREEN = REGISTRY.register("beach_parasol_green", () -> new BeachParasolGreenBlock());
    public static final RegistryObject<Block> BEACH_PARASOL_STRIPE_BLUE = REGISTRY.register("beach_parasol_stripe_blue", () -> new BeachParasolStripeRedBlock());
    public static final RegistryObject<Block> BEACH_PARASOL_STRIPE_RED = REGISTRY.register("beach_parasol_stripe_red", () -> new BeachParasolStripeRed1Block());
    public static final RegistryObject<Block> BEACH_PARASOL_STRIPE_CYAN = REGISTRY.register("beach_parasol_stripe_cyan", () -> new BeachParasolStripeCyanBlock());
    public static final RegistryObject<Block> BEACH_PARASOL_STRIPE_YELLOW = REGISTRY.register("beach_parasol_stripe_yellow", () -> new BeachParasolStripeYellowBlock());
    public static final RegistryObject<Block> BEACH_PARASOL_STRIPE_PINK = REGISTRY.register("beach_parasol_stripe_pink", () -> new BeachParasolStripePinkBlock());
    public static final RegistryObject<Block> BEACH_PARASOL_STRIPE_GREEN = REGISTRY.register("beach_parasol_stripe_green", () -> new BeachParasolStripeGreenBlock());
    public static final RegistryObject<Block> BEACH_PARASOL_CLOTH_WHITE = REGISTRY.register("beach_parasol_cloth_white", () -> new BeachParasolClothWhiteBlock());
    public static final RegistryObject<Block> BEACH_PARASOL_CLOTH_GREEN = REGISTRY.register("beach_parasol_cloth_green", () -> new BeachParasolClothGreenBlock());
    public static final RegistryObject<Block> BEACH_PARASOL_CLOTH_BLACK = REGISTRY.register("beach_parasol_cloth_black", () -> new BeachParasolClothBlackBlock());
    public static final RegistryObject<Block> BEACH_PARASOL_CLOTH_BROWN = REGISTRY.register("beach_parasol_cloth_brown", () -> new BeachParasolClothBrownBlock());
    public static final RegistryObject<Block> PICNIC_SHEET = REGISTRY.register("picnic_sheet", () -> new PicnicSheetBlock());
    public static final RegistryObject<Block> COOLER_BOX = REGISTRY.register("cooler_box", () -> new CoolerBoxBlock());
    public static final RegistryObject<Block> BOLLARD = REGISTRY.register("bollard", () -> new BollardBlock());
    public static final RegistryObject<Block> FENDER = REGISTRY.register("fender", () -> new FenderBlock());
    public static final RegistryObject<Block> WHEEL_STOP = REGISTRY.register("wheel_stop", () -> new WheelStopBlock());
    public static final RegistryObject<Block> PIER = REGISTRY.register("pier", () -> new PierBlock());
    public static final RegistryObject<Block> PIER_PILLAR = REGISTRY.register("pier_pillar", () -> new PierPillarBlock());
    public static final RegistryObject<Block> BEACH_SAND_BLOCK = REGISTRY.register("beach_sand_block", () -> new BeachSandBlockBlock());
    public static final RegistryObject<Block> SHELL = REGISTRY.register("shell", () -> new ShellBlock());
    public static final RegistryObject<Block> SNAIL = REGISTRY.register("snail", () -> new SnailBlock());
    public static final RegistryObject<Block> STARFISH = REGISTRY.register("starfish", () -> new StarfishBlock());
    public static final RegistryObject<Block> DRIFTWOOD = REGISTRY.register("driftwood", () -> new DriftwoodBlock());
    public static final RegistryObject<Block> SEAWEED = REGISTRY.register("seaweed", () -> new SeaweedBlock());
    public static final RegistryObject<Block> BUOY_BLOCK = REGISTRY.register("buoy_block", () -> new BuoyBlockBlock());
    public static final RegistryObject<Block> FAN_COVER = REGISTRY.register("fan_cover", () -> new FanCoverBlock());
    public static final RegistryObject<Block> LP_GAS_CYLINDER = REGISTRY.register("lp_gas_cylinder", () -> new LpGasCylinderBlock());
    public static final RegistryObject<Block> WATER_HEATER = REGISTRY.register("water_heater", () -> new WaterHeaterBlock());
    public static final RegistryObject<Block> SHUTTER_CASE = REGISTRY.register("shutter_case", () -> new ShutterCaseBlock());
    public static final RegistryObject<Block> GUARDRAIL_WHITE = REGISTRY.register("guardrail_white", () -> new GuardrailWhiteBlock());
    public static final RegistryObject<Block> CURB = REGISTRY.register("curb", () -> new CurbBlock());
    public static final RegistryObject<Block> WOOD_WALL = REGISTRY.register("wood_wall", () -> new WoodWallBlock());
    public static final RegistryObject<Block> CONCRETE_WALL = REGISTRY.register("concrete_wall", () -> new ConcreteWallBlock());
    public static final RegistryObject<Block> CONCRETE_WALL_WINDHOLE = REGISTRY.register("concrete_wall_windhole", () -> new ConcreteWallWindholeBlock());
    public static final RegistryObject<Block> TOTAN_WALL = REGISTRY.register("totan_wall", () -> new TotanWallBlock());
    public static final RegistryObject<Block> GREEN_FENCE = REGISTRY.register("green_fence", () -> new GreenFenceBlock());
    public static final RegistryObject<Block> GAS_METER = REGISTRY.register("gas_meter", () -> new GasMeterBlock());
    public static final RegistryObject<Block> ENGAWA = REGISTRY.register("engawa", () -> new EngawaBlock());
    public static final RegistryObject<Block> WOOD_TOBUKURO_ORANGE_BROWN = REGISTRY.register("wood_tobukuro_orange_brown", () -> new WoodTobukuroBrownBlock());
    public static final RegistryObject<Block> WOOD_TOBUKURO_LIGHT_BROWN = REGISTRY.register("wood_tobukuro_light_brown", () -> new WoodTobukuroLightBrownBlock());
    public static final RegistryObject<Block> WOOD_TOBUKURO_BROWN = REGISTRY.register("wood_tobukuro_brown", () -> new WoodTobukuroBrown1Block());
    public static final RegistryObject<Block> WOOD_TOBUKURO_DARK_BROWN = REGISTRY.register("wood_tobukuro_dark_brown", () -> new WoodTobukuroDarkBlock());
    public static final RegistryObject<Block> WOOD_TOBUKURO_RED = REGISTRY.register("wood_tobukuro_red", () -> new WoodTobukuroRedBlock());
    public static final RegistryObject<Block> HISASI = REGISTRY.register("hisasi", () -> new HisasiBlock());
    public static final RegistryObject<Block> WOOD_WINDOW_ORANGE_BROWN = REGISTRY.register("wood_window_orange_brown", () -> new WoodWindowOrangeBrownBlock());
    public static final RegistryObject<Block> WOOD_WINDOW_LIGHT_BROWN = REGISTRY.register("wood_window_light_brown", () -> new WoodWindowLightBrownBlock());
    public static final RegistryObject<Block> WOOD_WINDOW_BROWN = REGISTRY.register("wood_window_brown", () -> new WoodWindowBrownBlock());
    public static final RegistryObject<Block> WOOD_WINDOW_DARK_BROWN = REGISTRY.register("wood_window_dark_brown", () -> new WoodWindowDarkBlock());
    public static final RegistryObject<Block> WOOD_WINDOW_RED = REGISTRY.register("wood_window_red", () -> new WoodWindowRedBlock());
    public static final RegistryObject<Block> ALM_WINDOW = REGISTRY.register("alm_window", () -> new AlmWindowBlock());
    public static final RegistryObject<Block> WOOD_PILLAR_ORANGE_BROWN = REGISTRY.register("wood_pillar_orange_brown", () -> new WoodPillarOrangeBrownBlock());
    public static final RegistryObject<Block> WOOD_PILLAR_LIGHT_BROWN = REGISTRY.register("wood_pillar_light_brown", () -> new WoodpillarLightBrownBlock());
    public static final RegistryObject<Block> WOOD_PILLAR_BROWN = REGISTRY.register("wood_pillar_brown", () -> new WoodPillarBrownBlock());
    public static final RegistryObject<Block> WOOD_PILLAR_DARK_BROWN = REGISTRY.register("wood_pillar_dark_brown", () -> new WoodPillarDarkBlock());
    public static final RegistryObject<Block> WOOD_PILLAR_RED = REGISTRY.register("wood_pillar_red", () -> new WoodPillarRedBlock());
    public static final RegistryObject<Block> METAL_PILLAR_WHITE = REGISTRY.register("metal_pillar_white", () -> new MetalPillarBlock());
    public static final RegistryObject<Block> METAL_PILLAR_BROWN = REGISTRY.register("metal_pillar_brown", () -> new MetalPillarBrownBlock());
    public static final RegistryObject<Block> METAL_PILLAR_BLACK = REGISTRY.register("metal_pillar_black", () -> new MetalPillarBlackBlock());
    public static final RegistryObject<Block> METAL_PILLAR_YELLOW = REGISTRY.register("metal_pillar_yellow", () -> new MetalPillarYellowBlock());
    public static final RegistryObject<Block> METAL_PILLAR_GREEN = REGISTRY.register("metal_pillar_green", () -> new MetalPillarGreenBlock());
    public static final RegistryObject<Block> DRAIN_PIPE = REGISTRY.register("drain_pipe", () -> new DrainPipeBlock());
    public static final RegistryObject<Block> METAL_STAIR_WHITE = REGISTRY.register("metal_stair_white", () -> new MetalStairWhiteBlock());
    public static final RegistryObject<Block> METAL_STAIR_BROWN = REGISTRY.register("metal_stair_brown", () -> new MetalStairBrownBlock());
    public static final RegistryObject<Block> METAL_STAIR_BLACK = REGISTRY.register("metal_stair_black", () -> new MetalStairBlackBlock());
    public static final RegistryObject<Block> METAL_STAIR_YELLOW = REGISTRY.register("metal_stair_yellow", () -> new MetalStairYellowBlock());
    public static final RegistryObject<Block> METAL_STAIR_GREEN = REGISTRY.register("metal_stair_green", () -> new MetalStairGreenBlock());
    public static final RegistryObject<Block> METAL_FENCE_WHITE = REGISTRY.register("metal_fence_white", () -> new MetalFenceWhiteBlock());
    public static final RegistryObject<Block> METAL_FENCE_BROWN = REGISTRY.register("metal_fence_brown", () -> new MetalFenceBrownBlock());
    public static final RegistryObject<Block> METAL_FENCE_BLACK = REGISTRY.register("metal_fence_black", () -> new MetalFenceBlackBlock());
    public static final RegistryObject<Block> METAL_FENCE_YELLOW = REGISTRY.register("metal_fence_yellow", () -> new MetalFenceYellowBlock());
    public static final RegistryObject<Block> METAL_FENCE_GREEN = REGISTRY.register("metal_fence_green", () -> new MetalFenceGreenBlock());
    public static final RegistryObject<Block> METAL_FLOOR_WHITE = REGISTRY.register("metal_floor_white", () -> new MetalFloorWhiteBlock());
    public static final RegistryObject<Block> METAL_FLOOR_BROWN = REGISTRY.register("metal_floor_brown", () -> new MetalFloorBrownBlock());
    public static final RegistryObject<Block> METAL_FLOOR_BLACK = REGISTRY.register("metal_floor_black", () -> new MetalFloorBlackBlock());
    public static final RegistryObject<Block> METAL_FLOOR_YELLOW = REGISTRY.register("metal_floor_yellow", () -> new MetalfloorYellowBlock());
    public static final RegistryObject<Block> METAL_FLOOR_GREEN = REGISTRY.register("metal_floor_green", () -> new MetalFloorGreenBlock());
    public static final RegistryObject<Block> OLD_CONCRETE_STAIR = REGISTRY.register("old_concrete_stair", () -> new OldConcreteStairBlock());
    public static final RegistryObject<Block> OUTDOOR_SPOTLIGHT = REGISTRY.register("outdoor_spotlight", () -> new OutdoorSpotlightBlock());
    public static final RegistryObject<Block> ROOF_SIGNBOARD_BASE = REGISTRY.register("roof_signboard_base", () -> new RoofSignboardBaseBlock());
    public static final RegistryObject<Block> UTILITY_POLE_BOTTOM = REGISTRY.register("utility_pole_bottom", () -> new UtilityPoleBottomBlock());
    public static final RegistryObject<Block> UTILITY_POLE_MIDDLE = REGISTRY.register("utility_pole_middle", () -> new UtilityPoleMiddleBlock());
    public static final RegistryObject<Block> UTILITY_POLE_TOP = REGISTRY.register("utility_pole_top", () -> new UtilityPoleTopBlock());
    public static final RegistryObject<Block> ELECTRICAL_WIRE = REGISTRY.register("electrical_wire", () -> new ElectricalWireBlock());
    public static final RegistryObject<Block> UTILITY_POLE_PART = REGISTRY.register("utility_pole_part", () -> new UtilityPolePartBlock());
    public static final RegistryObject<Block> UTILITY_POLE_SIGNS = REGISTRY.register("utility_pole_signs", () -> new UtilityPoleSignsBlock());
    public static final RegistryObject<Block> UTILITY_POLE_LIGHT = REGISTRY.register("utility_pole_light", () -> new UtilityPoleLightBlock());
    public static final RegistryObject<Block> RANMA_ORANGE_BROWN = REGISTRY.register("ranma_orange_brown", () -> new RanmaOrangeBrownBlock());
    public static final RegistryObject<Block> RANMA_LIGHT_BROWN = REGISTRY.register("ranma_light_brown", () -> new RanmaLightBrownBlock());
    public static final RegistryObject<Block> RANMA_BROWN = REGISTRY.register("ranma_brown", () -> new RanmaBrownBlock());
    public static final RegistryObject<Block> ELECTRICITY_METER = REGISTRY.register("electricity_meter", () -> new ElectricityMeterBlock());
    public static final RegistryObject<Block> MONOHOSI = REGISTRY.register("monohosi", () -> new MonohosiBlock());
    public static final RegistryObject<Block> MONOHOSI_BAR = REGISTRY.register("monohosi_bar", () -> new MonohosiBarBlock());
    public static final RegistryObject<Block> BUILDING_MAILBOX = REGISTRY.register("building_mailbox", () -> new BuildingMailboxBlock());
    public static final RegistryObject<Block> TOTAN_ROOF_BLUE_BLOCK = REGISTRY.register("totan_roof_blue_block", () -> new TotanRoofBlueBlockBlock());
    public static final RegistryObject<Block> TOTAN_ROOF_RED_BLOCK = REGISTRY.register("totan_roof_red_block", () -> new TotanRoofRedBlockBlock());
    public static final RegistryObject<Block> TOTAN_ROOF_GRAY_BLOCK = REGISTRY.register("totan_roof_gray_block", () -> new TotanRoofGrayBlockBlock());
    public static final RegistryObject<Block> KAWARA_BLACK_BLOCK = REGISTRY.register("kawara_black_block", () -> new KawaraBlackBlockBlock());
    public static final RegistryObject<Block> KAWARA_GRAY_BLOCK = REGISTRY.register("kawara_gray_block", () -> new KawaraGrayBlockBlock());
    public static final RegistryObject<Block> KAWARA_BLUE_BLOCK = REGISTRY.register("kawara_blue_block", () -> new KawaraBlueBlockBlock());
    public static final RegistryObject<Block> KAWARA_GREEN_BLOCK = REGISTRY.register("kawara_green_block", () -> new KawaraGreenBlockBlock());
    public static final RegistryObject<Block> KAWARA_ORANGE_BLOCK = REGISTRY.register("kawara_orange_block", () -> new KawaraOrangeBlockBlock());
    public static final RegistryObject<Block> KAWARA_ODD_BLACK_BLOCK = REGISTRY.register("kawara_odd_black_block", () -> new KawaraOddBlackBlockBlock());
    public static final RegistryObject<Block> KAWARA_ODD_GRAY_BLOCK = REGISTRY.register("kawara_odd_gray_block", () -> new KawaraOddGrayBlockBlock());
    public static final RegistryObject<Block> KAWARA_ODD_BLUE_BLOCK = REGISTRY.register("kawara_odd_blue_block", () -> new KawaraOddBlueBlockBlock());
    public static final RegistryObject<Block> KAWARA_ODD_GREEN_BLOCK = REGISTRY.register("kawara_odd_green_block", () -> new KawaraOddGreenBlockBlock());
    public static final RegistryObject<Block> KAWARA_ODD_ORANGE_BLOCK = REGISTRY.register("kawara_odd_orange_block", () -> new KawaraOddOrangeBlockBlock());
    public static final RegistryObject<Block> METAL_DOOR_WHITE_BLOCK = REGISTRY.register("metal_door_white_block", () -> new DoorMetalWhiteBlockBlock());
    public static final RegistryObject<Block> METAL_DOOR_YELLOW_BLOCK = REGISTRY.register("metal_door_yellow_block", () -> new DoorMetalYellowBlockBlock());
    public static final RegistryObject<Block> METAL_DOOR_GREEN_BLOCK = REGISTRY.register("metal_door_green_block", () -> new DoorMetalGreenBlockBlock());
    public static final RegistryObject<Block> METAL_DOOR_BROWN_BLOCK = REGISTRY.register("metal_door_brown_block", () -> new DoorMetalBrownBlockBlock());
    public static final RegistryObject<Block> METAL_DOOR_BLACK_BLOCK = REGISTRY.register("metal_door_black_block", () -> new DoorMetalBlackBlockBlock());
    public static final RegistryObject<Block> OLD_DOOR_BLOCK = REGISTRY.register("old_door_block", () -> new OldDoorBlockBlock());
    public static final RegistryObject<Block> METAL_DOOR_WINDOW_WHITE_BLOCK = REGISTRY.register("metal_door_window_white_block", () -> new MetalDoorWindowWhiteBlockBlock());
    public static final RegistryObject<Block> METAL_DOOR_WINDOW_YELLOW_BLOCK = REGISTRY.register("metal_door_window_yellow_block", () -> new MetalDoorWindowYellowBlockBlock());
    public static final RegistryObject<Block> METAL_DOOR_WINDOW_GREEN_BLOCK = REGISTRY.register("metal_door_window_green_block", () -> new MetalDoorWindowGreenBlockBlock());
    public static final RegistryObject<Block> METAL_DOOR_WINDOW_BROWN_BLOCK = REGISTRY.register("metal_door_window_brown_block", () -> new MetalDoorWindowBrownBlockBlock());
    public static final RegistryObject<Block> METAL_DOOR_WINDOW_BLACK_BLOCK = REGISTRY.register("metal_door_window_black_block", () -> new MetalDoorWindowBlackBlockBlock());
    public static final RegistryObject<Block> METAL_DOOR_TALL_WHITE_BLOCK = REGISTRY.register("metal_door_tall_white_block", () -> new MetalDoorTallWhiteBlockBlock());
    public static final RegistryObject<Block> METAL_DOOR_TALL_YELLOW_BLOCK = REGISTRY.register("metal_door_tall_yellow_block", () -> new MetalDoorTallYellowBlockBlock());
    public static final RegistryObject<Block> METAL_DOOR_TALL_GREEN_BLOCK = REGISTRY.register("metal_door_tall_green_block", () -> new MetalDoorTallGreenBlockBlock());
    public static final RegistryObject<Block> METAL_DOOR_TALL_BROWN_BLOCK = REGISTRY.register("metal_door_tall_brown_block", () -> new MetalDoorTallBrownBlockBlock());
    public static final RegistryObject<Block> METAL_DOOR_TALL_BLACK_BLOCK = REGISTRY.register("metal_door_tall_black_block", () -> new MetalDoorTallBlackBlockBlock());
    public static final RegistryObject<Block> METAL_DOOR_TALL_WINDOW_WHITE_BLOCK = REGISTRY.register("metal_door_tall_window_white_block", () -> new MetalDoorTallWindowWhiteBlockBlock());
    public static final RegistryObject<Block> METAL_DOOR_TALL_WINDOW_YELLOW_BLOCK = REGISTRY.register("metal_door_tall_window_yellow_block", () -> new MetalDoorTallWindowYellowBlockBlock());
    public static final RegistryObject<Block> METAL_DOOR_TALL_WINDOW_GREEN_BLOCK = REGISTRY.register("metal_door_tall_window_green_block", () -> new MetalDoorTallWindowGreenBlockBlock());
    public static final RegistryObject<Block> METAL_DOOR_TALL_WINDOW_BROWN_BLOCK = REGISTRY.register("metal_door_tall_window_brown_block", () -> new MetalDoorTallWindowBrownBlockBlock());
    public static final RegistryObject<Block> METAL_DOOR_TALL_WINDOW_BLACK_BLOCK = REGISTRY.register("metal_door_tall_window_black_block", () -> new MetalDoorTallWindowBlackBlockBlock());
    public static final RegistryObject<Block> OLD_DOOR_TALL_BLOCK = REGISTRY.register("old_door_tall_block", () -> new OldDoorTallBlockBlock());
    public static final RegistryObject<Block> UNDERWEAR = REGISTRY.register("underwear", () -> new UnderwearBlock());
    public static final RegistryObject<Block> CLOTH_DRESS = REGISTRY.register("cloth_dress", () -> new ClothDressBlock());
    public static final RegistryObject<Block> SLIDING_DOOR_BROWN_BLOCK = REGISTRY.register("sliding_door_brown_block", () -> new SlidingDoorBrownBlockBlock());
    public static final RegistryObject<Block> SLIDING_DOOR_LIGHT_BROWN_BLOCK = REGISTRY.register("sliding_door_light_brown_block", () -> new SlidingDoorLightBrownBlockBlock());
    public static final RegistryObject<Block> SLIDING_DOOR_ORANGE_BROWN_BLOCK = REGISTRY.register("sliding_door_orange_brown_block", () -> new SlidingDoorOrangeBrownBlockBlock());
    public static final RegistryObject<Block> SYOUJI_BROWN_BLOCK = REGISTRY.register("syouji_brown_block", () -> new SyoujiBrownBlockBlock());
    public static final RegistryObject<Block> SYOUJI_LIGHT_BROWN_BLOCK = REGISTRY.register("syouji_light_brown_block", () -> new SyoujiLightBrownBlockBlock());
    public static final RegistryObject<Block> SYOUJI_ORANGE_BROWN_BLOCK = REGISTRY.register("syouji_orange_brown_block", () -> new SyoujiOrangeBrownBlockBlock());
    public static final RegistryObject<Block> SYOUJIYUKIMI_BROWN_BLOCK = REGISTRY.register("syoujiyukimi_brown_block", () -> new SyoujiyukimiBrownBlockBlock());
    public static final RegistryObject<Block> SYOUJIYUKIMI_LIGHT_BROWN_BLOCK = REGISTRY.register("syoujiyukimi_light_brown_block", () -> new SyoujiyukimiLightBrownBlockBlock());
    public static final RegistryObject<Block> SYOUJIYUKIMI_ORANGE_BROWN_BLOCK = REGISTRY.register("syoujiyukimi_orange_brown_block", () -> new SyoujiyukimiOrangeBrownBlockBlock());
    public static final RegistryObject<Block> SLIDING_DOOR_TALL_BROWN_BLOCK = REGISTRY.register("sliding_door_tall_brown_block", () -> new SlidingDoorTallBrownBlockBlock());
    public static final RegistryObject<Block> SLIDING_DOOR_TALL_LIGHT_BROWN_BLOCK = REGISTRY.register("sliding_door_tall_light_brown_block", () -> new SlidingDoorTallLightBrownBlockBlock());
    public static final RegistryObject<Block> SLIDING_DOOR_TALL_ORANGE_BROWN_BLOCK = REGISTRY.register("sliding_door_tall_orange_brown_block", () -> new SlidingDoorTallOrangeBrownBlockBlock());
    public static final RegistryObject<Block> SYOUJI_TALL_BROWN_BLOCK = REGISTRY.register("syouji_tall_brown_block", () -> new SyoujiTallBrownBlockBlock());
    public static final RegistryObject<Block> SYOUJI_TALL_LIGHT_BROWN_BLOCK = REGISTRY.register("syouji_tall_light_brown_block", () -> new SyoujiTallLightBrownBlockBlock());
    public static final RegistryObject<Block> SYOUJI_TALL_ORANGE_BROWN_BLOCK = REGISTRY.register("syouji_tall_orange_brown_block", () -> new SyoujiTallOrangeBrownBlockBlock());
    public static final RegistryObject<Block> SYOUJIYUKIMI_TALL_BROWN_BLOCK = REGISTRY.register("syoujiyukimi_tall_brown_block", () -> new SyoujiyukimiTallBrownBlockBlock());
    public static final RegistryObject<Block> SYOUJIYUKIMI_TALL_LIGHT_BROWN_BLOCK = REGISTRY.register("syoujiyukimi_tall_light_brown_block", () -> new SyoujiyukimiTallLightBrownBlockBlock());
    public static final RegistryObject<Block> SYOUJIYUKIMI_TALL_ORANGE_BROWN_BLOCK = REGISTRY.register("syoujiyukimi_tall_orange_brown_block", () -> new SyoujiyukimiTallOrangeBrownBlockBlock());
    public static final RegistryObject<Block> HUSUMA_BLOCK = REGISTRY.register("husuma_block", () -> new HusumaBlockBlock());
    public static final RegistryObject<Block> HUSUMA_BLUE_LINE_BLOCK = REGISTRY.register("husuma_blue_line_block", () -> new HusumaBlueLineBlockBlock());
    public static final RegistryObject<Block> HUSUMA_INK_BLOCK = REGISTRY.register("husuma_ink_block", () -> new HusumaInkBlockBlock());
    public static final RegistryObject<Block> HUSUMA_SAKURA_BLOCK = REGISTRY.register("husuma_sakura_block", () -> new HusumaSakuraBlockBlock());
    public static final RegistryObject<Block> HUSUMA_TALL_BLOCK = REGISTRY.register("husuma_tall_block", () -> new HusumaTallBlockBlock());
    public static final RegistryObject<Block> HUSUMA_TALL_BLUE_LINE_BLOCK = REGISTRY.register("husuma_tall_blue_line_block", () -> new HusumaTallBlueLineBlockBlock());
    public static final RegistryObject<Block> HUSUMA_TALL_INK_BLOCK = REGISTRY.register("husuma_tall_ink_block", () -> new HusumaTallInkBlockBlock());
    public static final RegistryObject<Block> HUSUMA_TALL_SAKURA_BLCOK = REGISTRY.register("husuma_tall_sakura_blcok", () -> new HusumaTallSakuraBlcokBlock());
    public static final RegistryObject<Block> ALM_DOOR_BLOCK = REGISTRY.register("alm_door_block", () -> new AlmDoorBlockBlock());
    public static final RegistryObject<Block> DUCT = REGISTRY.register("duct", () -> new DuctBlock());
    public static final RegistryObject<Block> OLD_PIPE = REGISTRY.register("old_pipe", () -> new OldPipeBlock());
    public static final RegistryObject<Block> SITAMI_ITABARI_ORANGE_BROWN_SLAB = REGISTRY.register("sitami_itabari_orange_brown_slab", () -> new SitamiItabariOrangeBrownSlabBlock());
    public static final RegistryObject<Block> SITAMI_ITABARI_LIGHT_BROWN_SLAB = REGISTRY.register("sitami_itabari_light_brown_slab", () -> new SitamiItabariLightBrownSlabBlock());
    public static final RegistryObject<Block> SITAMI_ITABARI_BROWN_SLAB = REGISTRY.register("sitami_itabari_brown_slab", () -> new SitamiItabariBrownSlabBlock());
    public static final RegistryObject<Block> SITAMI_ITABARI_DARK_BROWN_SLAB = REGISTRY.register("sitami_itabari_dark_brown_slab", () -> new SitamiItabariDarkBrownSlabBlock());
    public static final RegistryObject<Block> SITAMI_ITABARI_RED_SLAB = REGISTRY.register("sitami_itabari_red_slab", () -> new SitamiItabariRedSlabBlock());
    public static final RegistryObject<Block> GLASS_ALM_WINDOW = REGISTRY.register("glass_alm_window", () -> new GlassAlmWindowBlock());
}

