/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  net.minecraft.world.item.BlockItem
 *  net.minecraft.world.item.Item
 *  net.minecraft.world.item.Item$Properties
 *  net.minecraft.world.level.block.Block
 *  net.minecraftforge.registries.DeferredRegister
 *  net.minecraftforge.registries.ForgeRegistries
 *  net.minecraftforge.registries.IForgeRegistry
 *  net.minecraftforge.registries.RegistryObject
 */
package rojiuramod.init;

import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.Block;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.IForgeRegistry;
import net.minecraftforge.registries.RegistryObject;
import rojiuramod.init.RojiuramodModBlocks;
import rojiuramod.item.AlmDoorItem;
import rojiuramod.item.AsphaltLayerCrack1Item;
import rojiuramod.item.AsphaltLayerDry1Item;
import rojiuramod.item.AsphaltLayerHole1Item;
import rojiuramod.item.AsphaltLayerLine1Item;
import rojiuramod.item.AsphaltLayerWet1Item;
import rojiuramod.item.AsphaltLayerWhite1Item;
import rojiuramod.item.BeachSandItem;
import rojiuramod.item.Beer1Item;
import rojiuramod.item.BenchItem;
import rojiuramod.item.BenchRedItem;
import rojiuramod.item.BenchWoodItem;
import rojiuramod.item.BuoyItem;
import rojiuramod.item.CansItem;
import rojiuramod.item.CardBoardBed1Item;
import rojiuramod.item.CoinItem;
import rojiuramod.item.DoorMetalBlackItem;
import rojiuramod.item.DoorMetalBrownItem;
import rojiuramod.item.DoorMetalGreenItem;
import rojiuramod.item.DoorMetalWhiteItem;
import rojiuramod.item.DoormetalYellowItem;
import rojiuramod.item.DuctitemItem;
import rojiuramod.item.FloatingRingItem;
import rojiuramod.item.GravityStickItem;
import rojiuramod.item.HusumaBlueLineItem;
import rojiuramod.item.HusumaInkItem;
import rojiuramod.item.HusumaItem;
import rojiuramod.item.HusumaSakuraItem;
import rojiuramod.item.HusumaTallBlueLineItem;
import rojiuramod.item.HusumaTallInkItem;
import rojiuramod.item.HusumaTallItem;
import rojiuramod.item.HusumaTallSakuraItem;
import rojiuramod.item.IceCandy1Item;
import rojiuramod.item.InvisibleLight12Item;
import rojiuramod.item.InvisibleLight4Item;
import rojiuramod.item.InvisibleLight8Item;
import rojiuramod.item.KawaraBlackItem;
import rojiuramod.item.KawaraBlueItem;
import rojiuramod.item.KawaraGrayItem;
import rojiuramod.item.KawaraGreenItem;
import rojiuramod.item.KawaraOddBlackItem;
import rojiuramod.item.KawaraOddBlueItem;
import rojiuramod.item.KawaraOddGrayItem;
import rojiuramod.item.KawaraOddGreenItem;
import rojiuramod.item.KawaraOddOrangeItem;
import rojiuramod.item.KawaraOrangeItem;
import rojiuramod.item.LnvisibleLightItem;
import rojiuramod.item.MetalDoorTallBlackItem;
import rojiuramod.item.MetalDoorTallBorwnItem;
import rojiuramod.item.MetalDoorTallGreenItem;
import rojiuramod.item.MetalDoorTallWhiteItem;
import rojiuramod.item.MetalDoorTallWindowBlackItem;
import rojiuramod.item.MetalDoorTallWindowBrownItem;
import rojiuramod.item.MetalDoorTallWindowGreenItem;
import rojiuramod.item.MetalDoorTallWindowWhiteItem;
import rojiuramod.item.MetalDoorTallWindowYellowItem;
import rojiuramod.item.MetalDoorTallYellowItem;
import rojiuramod.item.MetalDoorWindowBlackItem;
import rojiuramod.item.MetalDoorWindowBrownItem;
import rojiuramod.item.MetalDoorWindowGreenItem;
import rojiuramod.item.MetalDoorWindowWhiteItem;
import rojiuramod.item.MetalDoorWindowYellowItem;
import rojiuramod.item.OldDoorItem;
import rojiuramod.item.OldDoorTallItem;
import rojiuramod.item.OldPipeItemItem;
import rojiuramod.item.Poster1X1Item;
import rojiuramod.item.Poster1X2Item;
import rojiuramod.item.Poster1X4Item;
import rojiuramod.item.Poster1X5Item;
import rojiuramod.item.Poster2X1Item;
import rojiuramod.item.Poster2X2Item;
import rojiuramod.item.Poster2X3Item;
import rojiuramod.item.Poster2X6Item;
import rojiuramod.item.Poster4X4Item;
import rojiuramod.item.SlidingDoorBrownItem;
import rojiuramod.item.SlidingDoorLightBrownItem;
import rojiuramod.item.SlidingDoorOrangeBrownItem;
import rojiuramod.item.SlidingDoorTallBrownItem;
import rojiuramod.item.SlidingDoorTallLightBrownItem;
import rojiuramod.item.SlidingDoorTallOrangeBrownItem;
import rojiuramod.item.SyoujiBrownItem;
import rojiuramod.item.SyoujiLightBrownItem;
import rojiuramod.item.SyoujiOrangeBrownItem;
import rojiuramod.item.SyoujiTallBrownItem;
import rojiuramod.item.SyoujiTallLightBrownItem;
import rojiuramod.item.SyoujiTallOrangeBrownItem;
import rojiuramod.item.SyoujiyukimiBrownItem;
import rojiuramod.item.SyoujiyukimiLightBrownItem;
import rojiuramod.item.SyoujiyukimiOrangeBrownItem;
import rojiuramod.item.SyoujiyukimiTallBrownItem;
import rojiuramod.item.SyoujiyukimiTallLightBrownItem;
import rojiuramod.item.SyoujiyukimiTallOrangeBrownItem;
import rojiuramod.item.TatamiGreen1Item;
import rojiuramod.item.TatamiYellowItem;
import rojiuramod.item.TotanRoofBlueItem;
import rojiuramod.item.TotanRoofGrayItem;
import rojiuramod.item.TotanRoofRedItem;
import rojiuramod.item.VendingMachineItem;

public class RojiuramodModItems {
    public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create((IForgeRegistry)ForgeRegistries.ITEMS, (String)"rojiuramod");
    public static final RegistryObject<Item> ASPHALT_DRY = RojiuramodModItems.block(RojiuramodModBlocks.ASPHALT_DRY);
    public static final RegistryObject<Item> ASPHALT_LINE = RojiuramodModItems.block(RojiuramodModBlocks.ASPHALT_LINE);
    public static final RegistryObject<Item> ASPHALT_WHITE = RojiuramodModItems.block(RojiuramodModBlocks.ASPHALT_WHITE);
    public static final RegistryObject<Item> ASPHALT_CRACK = RojiuramodModItems.block(RojiuramodModBlocks.ASPHALT_CRACK);
    public static final RegistryObject<Item> ASPHALT_HOLE = RojiuramodModItems.block(RojiuramodModBlocks.ASPHALT_HOLE);
    public static final RegistryObject<Item> ASPHALT_WET = RojiuramodModItems.block(RojiuramodModBlocks.ASPHALT_WET);
    public static final RegistryObject<Item> COBBLE_STONE = RojiuramodModItems.block(RojiuramodModBlocks.COBBLE_STONE);
    public static final RegistryObject<Item> STONE_WALL = RojiuramodModItems.block(RojiuramodModBlocks.STONE_WALL);
    public static final RegistryObject<Item> POSTER_CONCRETE = RojiuramodModItems.block(RojiuramodModBlocks.POSTER_CONCRETE);
    public static final RegistryObject<Item> GRAFFITI_CONCRETE = RojiuramodModItems.block(RojiuramodModBlocks.GRAFFITI_CONCRETE);
    public static final RegistryObject<Item> DIRTY_CONCRETE = RojiuramodModItems.block(RojiuramodModBlocks.DIRTY_CONCRETE);
    public static final RegistryObject<Item> OLD_CONCREAT = RojiuramodModItems.block(RojiuramodModBlocks.OLD_CONCREAT);
    public static final RegistryObject<Item> RETAINING_WALL = RojiuramodModItems.block(RojiuramodModBlocks.RETAINING_WALL);
    public static final RegistryObject<Item> STUCCO = RojiuramodModItems.block(RojiuramodModBlocks.STUCCO);
    public static final RegistryObject<Item> STREET_GUTTER = RojiuramodModItems.block(RojiuramodModBlocks.STREET_GUTTER);
    public static final RegistryObject<Item> WOOD_FLOOR_ORANGE_BROWN = RojiuramodModItems.block(RojiuramodModBlocks.WOOD_FLOOR_ORANGE_BROWN);
    public static final RegistryObject<Item> WOOD_FLOOR_LIGHT_BROWN = RojiuramodModItems.block(RojiuramodModBlocks.WOOD_FLOOR_LIGHT_BROWN);
    public static final RegistryObject<Item> WOOD_FLOOR_BROWN = RojiuramodModItems.block(RojiuramodModBlocks.WOOD_FLOOR_BROWN);
    public static final RegistryObject<Item> WOOD_FLOOR_DARK_BROWN = RojiuramodModItems.block(RojiuramodModBlocks.WOOD_FLOOR_DARK_BROWN);
    public static final RegistryObject<Item> WOOD_FLOOR_RED = RojiuramodModItems.block(RojiuramodModBlocks.WOOD_FLOOR_RED);
    public static final RegistryObject<Item> PLY_WOOD_ORANGE_BROWN = RojiuramodModItems.block(RojiuramodModBlocks.PLY_WOOD_ORANGE_BROWN);
    public static final RegistryObject<Item> PLY_WOOD_LIGHT_BROWN = RojiuramodModItems.block(RojiuramodModBlocks.PLY_WOOD_LIGHT_BROWN);
    public static final RegistryObject<Item> PLY_WOOD_BROWN = RojiuramodModItems.block(RojiuramodModBlocks.PLY_WOOD_BROWN);
    public static final RegistryObject<Item> PLY_WOOD_DARK_BROWN = RojiuramodModItems.block(RojiuramodModBlocks.PLY_WOOD_DARK_BROWN);
    public static final RegistryObject<Item> PLY_WOOD_RED = RojiuramodModItems.block(RojiuramodModBlocks.PLY_WOOD_RED);
    public static final RegistryObject<Item> STUCCO_WOOD_ORANGE_BROWN = RojiuramodModItems.block(RojiuramodModBlocks.STUCCO_WOOD_ORANGE_BROWN);
    public static final RegistryObject<Item> STUCCO_WOOD_LIGHT_BROWN = RojiuramodModItems.block(RojiuramodModBlocks.STUCCO_WOOD_LIGHT_BROWN);
    public static final RegistryObject<Item> STUCCO_WOOD_BROWN = RojiuramodModItems.block(RojiuramodModBlocks.STUCCO_WOOD_BROWN);
    public static final RegistryObject<Item> STUCCO_WOOD_DARK_BROWN = RojiuramodModItems.block(RojiuramodModBlocks.STUCCO_WOOD_DARK_BROWN);
    public static final RegistryObject<Item> STUCCO_WOOD_RED = RojiuramodModItems.block(RojiuramodModBlocks.STUCCO_WOOD_RED);
    public static final RegistryObject<Item> SITAMI_ITABARI_ORANGE_BROWN = RojiuramodModItems.block(RojiuramodModBlocks.SITAMI_ITABARI_ORANGE_BROWN);
    public static final RegistryObject<Item> SITAMI_ITABARI_LIGHT_BROWN = RojiuramodModItems.block(RojiuramodModBlocks.SITAMI_ITABARI_LIGHT_BROWN);
    public static final RegistryObject<Item> SITAMI_ITABARI_BROWN = RojiuramodModItems.block(RojiuramodModBlocks.SITAMI_ITABARI_BROWN);
    public static final RegistryObject<Item> SITAMI_ITABARI_DARK_BROWN = RojiuramodModItems.block(RojiuramodModBlocks.SITAMI_ITABARI_DARK_BROWN);
    public static final RegistryObject<Item> SITAMI_ITABARI_RED = RojiuramodModItems.block(RojiuramodModBlocks.SITAMI_ITABARI_RED);
    public static final RegistryObject<Item> CONCRETE_RED = RojiuramodModItems.block(RojiuramodModBlocks.CONCRETE_RED);
    public static final RegistryObject<Item> CONCRETE_MAGENTA = RojiuramodModItems.block(RojiuramodModBlocks.CONCRETE_MAGENTA);
    public static final RegistryObject<Item> CONCRETE_PINK = RojiuramodModItems.block(RojiuramodModBlocks.CONCRETE_PINK);
    public static final RegistryObject<Item> CONCRETE_ORANGE = RojiuramodModItems.block(RojiuramodModBlocks.CONCRETE_ORANGE);
    public static final RegistryObject<Item> CONCRETE_BROWN = RojiuramodModItems.block(RojiuramodModBlocks.CONCRETE_BROWN);
    public static final RegistryObject<Item> CONCRETE_YELLOW = RojiuramodModItems.block(RojiuramodModBlocks.CONCRETE_YELLOW);
    public static final RegistryObject<Item> CONCRETE_GREEN = RojiuramodModItems.block(RojiuramodModBlocks.CONCRETE_GREEN);
    public static final RegistryObject<Item> CONCRETE_LIME = RojiuramodModItems.block(RojiuramodModBlocks.CONCRETE_LIME);
    public static final RegistryObject<Item> CONCRETE_CYAN = RojiuramodModItems.block(RojiuramodModBlocks.CONCRETE_CYAN);
    public static final RegistryObject<Item> CONCRETE_LIGHT_BLUE = RojiuramodModItems.block(RojiuramodModBlocks.CONCRETE_LIGHT_BLUE);
    public static final RegistryObject<Item> CONCRETE_BLUE = RojiuramodModItems.block(RojiuramodModBlocks.CONCRETE_BLUE);
    public static final RegistryObject<Item> CONCRETE_PURPLE = RojiuramodModItems.block(RojiuramodModBlocks.CONCRETE_PURPLE);
    public static final RegistryObject<Item> CONCRETE_WHITE = RojiuramodModItems.block(RojiuramodModBlocks.CONCRETE_WHITE);
    public static final RegistryObject<Item> CONCRETE_SILVER = RojiuramodModItems.block(RojiuramodModBlocks.CONCRETE_SILVER);
    public static final RegistryObject<Item> CONCRETE_GRAY = RojiuramodModItems.block(RojiuramodModBlocks.CONCRETE_GRAY);
    public static final RegistryObject<Item> CONCRETE_BLACK = RojiuramodModItems.block(RojiuramodModBlocks.CONCRETE_BLACK);
    public static final RegistryObject<Item> MORTAR_WHITE = RojiuramodModItems.block(RojiuramodModBlocks.MORTAR_WHITE);
    public static final RegistryObject<Item> MORTAR_CREAM = RojiuramodModItems.block(RojiuramodModBlocks.MORTAR_CREAM);
    public static final RegistryObject<Item> MORTAR_GRAY = RojiuramodModItems.block(RojiuramodModBlocks.MORTAR_GRAY);
    public static final RegistryObject<Item> MORTAR_YELLOW = RojiuramodModItems.block(RojiuramodModBlocks.MORTAR_YELLOW);
    public static final RegistryObject<Item> MORTAR_ORANGE = RojiuramodModItems.block(RojiuramodModBlocks.MORTAR_ORANGE);
    public static final RegistryObject<Item> MORTAR_PINK = RojiuramodModItems.block(RojiuramodModBlocks.MORTAR_PINK);
    public static final RegistryObject<Item> MORTAR_GREEN = RojiuramodModItems.block(RojiuramodModBlocks.MORTAR_GREEN);
    public static final RegistryObject<Item> MORTAR_LIGHT_BLUE = RojiuramodModItems.block(RojiuramodModBlocks.MORTAR_LIGHT_BLUE);
    public static final RegistryObject<Item> MODERN_BRICK_WHITE = RojiuramodModItems.block(RojiuramodModBlocks.MODERN_BRICK_WHITE);
    public static final RegistryObject<Item> MODERN_BRICK_YELLOW = RojiuramodModItems.block(RojiuramodModBlocks.MODERN_BRICK_YELLOW);
    public static final RegistryObject<Item> MODERN_BRICK_ORANGE = RojiuramodModItems.block(RojiuramodModBlocks.MODERN_BRICK_ORANGE);
    public static final RegistryObject<Item> MODERN_BRICK_BLUE = RojiuramodModItems.block(RojiuramodModBlocks.MODERN_BRICK_BLUE);
    public static final RegistryObject<Item> MODERN_BRICK_GRAY = RojiuramodModItems.block(RojiuramodModBlocks.MODERN_BRICK_GRAY);
    public static final RegistryObject<Item> MODERN_BRICK_PINK = RojiuramodModItems.block(RojiuramodModBlocks.MODERN_BRICK_PINK);
    public static final RegistryObject<Item> MODERN_BRICK_GREEN = RojiuramodModItems.block(RojiuramodModBlocks.MODERN_BRICK_GREEN);
    public static final RegistryObject<Item> MODERN_BRICK_CREAM = RojiuramodModItems.block(RojiuramodModBlocks.MODERN_BRICK_CREAM);
    public static final RegistryObject<Item> MODERN_TILE_WHITE = RojiuramodModItems.block(RojiuramodModBlocks.MODERN_TILE_WHITE);
    public static final RegistryObject<Item> MODERN_TILE_YELLOW = RojiuramodModItems.block(RojiuramodModBlocks.MODERN_TILE_YELLOW);
    public static final RegistryObject<Item> MODERN_TILE_ORANGE = RojiuramodModItems.block(RojiuramodModBlocks.MODERN_TILE_ORANGE);
    public static final RegistryObject<Item> MODERN_TILE_GREEN = RojiuramodModItems.block(RojiuramodModBlocks.MODERN_TILE_GREEN);
    public static final RegistryObject<Item> MODERN_TILE_BLUE = RojiuramodModItems.block(RojiuramodModBlocks.MODERN_TILE_BLUE);
    public static final RegistryObject<Item> MODERN_TILE_GRAY = RojiuramodModItems.block(RojiuramodModBlocks.MODERN_TILE_GRAY);
    public static final RegistryObject<Item> MODERN_TILE_PINK = RojiuramodModItems.block(RojiuramodModBlocks.MODERN_TILE_PINK);
    public static final RegistryObject<Item> MODERN_TILE_CREAM = RojiuramodModItems.block(RojiuramodModBlocks.MODERN_TILE_CREAM);
    public static final RegistryObject<Item> TOTAN_S_BLUE = RojiuramodModItems.block(RojiuramodModBlocks.TOTAN_S_BLUE);
    public static final RegistryObject<Item> TOTAN_S_WHITE = RojiuramodModItems.block(RojiuramodModBlocks.TOTAN_S_WHITE);
    public static final RegistryObject<Item> TOTAN_S_PINK = RojiuramodModItems.block(RojiuramodModBlocks.TOTAN_S_PINK);
    public static final RegistryObject<Item> TOTAN_S_YELLOW = RojiuramodModItems.block(RojiuramodModBlocks.TOTAN_S_YELLOW);
    public static final RegistryObject<Item> TOTAN_S_BROWN = RojiuramodModItems.block(RojiuramodModBlocks.TOTAN_S_BROWN);
    public static final RegistryObject<Item> TOTAN_S_GRAY = RojiuramodModItems.block(RojiuramodModBlocks.TOTAN_S_GRAY);
    public static final RegistryObject<Item> TOTAN_S_GREEN = RojiuramodModItems.block(RojiuramodModBlocks.TOTAN_S_GREEN);
    public static final RegistryObject<Item> TOTAN_S_RED = RojiuramodModItems.block(RojiuramodModBlocks.TOTAN_S_RED);
    public static final RegistryObject<Item> TOTAN_L_BLUE = RojiuramodModItems.block(RojiuramodModBlocks.TOTAN_L_BLUE);
    public static final RegistryObject<Item> TOTAN_L_WHITE = RojiuramodModItems.block(RojiuramodModBlocks.TOTAN_L_WHITE);
    public static final RegistryObject<Item> TOTAN_L_PINK = RojiuramodModItems.block(RojiuramodModBlocks.TOTAN_L_PINK);
    public static final RegistryObject<Item> TOTAN_L_YELLOW = RojiuramodModItems.block(RojiuramodModBlocks.TOTAN_L_YELLOW);
    public static final RegistryObject<Item> TOTAN_L_BROWN = RojiuramodModItems.block(RojiuramodModBlocks.TOTAN_L_BROWN);
    public static final RegistryObject<Item> TOTAN_L_GRAY = RojiuramodModItems.block(RojiuramodModBlocks.TOTAN_L_GRAY);
    public static final RegistryObject<Item> TOTAN_L_GREEN = RojiuramodModItems.block(RojiuramodModBlocks.TOTAN_L_GREEN);
    public static final RegistryObject<Item> TOTAN_L_ORANGE = RojiuramodModItems.block(RojiuramodModBlocks.TOTAN_L_ORANGE);
    public static final RegistryObject<Item> SHUTTER_WHITE = RojiuramodModItems.block(RojiuramodModBlocks.SHUTTER_WHITE);
    public static final RegistryObject<Item> SHUTTER_BLUE = RojiuramodModItems.block(RojiuramodModBlocks.SHUTTER_BLUE);
    public static final RegistryObject<Item> SHUTTER_BROWN = RojiuramodModItems.block(RojiuramodModBlocks.SHUTTER_BROWN);
    public static final RegistryObject<Item> SHUTTER_GRAY = RojiuramodModItems.block(RojiuramodModBlocks.SHUTTER_GRAY);
    public static final RegistryObject<Item> PAPER_LANTERN = RojiuramodModItems.block(RojiuramodModBlocks.PAPER_LANTERN);
    public static final RegistryObject<Item> GARBAGE_BASKET = RojiuramodModItems.block(RojiuramodModBlocks.GARBAGE_BASKET);
    public static final RegistryObject<Item> WATERING_POT = RojiuramodModItems.block(RojiuramodModBlocks.WATERING_POT);
    public static final RegistryObject<Item> MORNING_GLORY = RojiuramodModItems.block(RojiuramodModBlocks.MORNING_GLORY);
    public static final RegistryObject<Item> MANHOLE = RojiuramodModItems.block(RojiuramodModBlocks.MANHOLE);
    public static final RegistryObject<Item> BEER_CASE = RojiuramodModItems.block(RojiuramodModBlocks.BEER_CASE);
    public static final RegistryObject<Item> BEER_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.BEER_BLOCK);
    public static final RegistryObject<Item> BEER_CASE_RED = RojiuramodModItems.block(RojiuramodModBlocks.BEER_CASE_RED);
    public static final RegistryObject<Item> STRONG_GRASS_A = RojiuramodModItems.block(RojiuramodModBlocks.STRONG_GRASS_A);
    public static final RegistryObject<Item> STRONG_GRASS_B = RojiuramodModItems.block(RojiuramodModBlocks.STRONG_GRASS_B);
    public static final RegistryObject<Item> EMERGENCY_LIGHT = RojiuramodModItems.block(RojiuramodModBlocks.EMERGENCY_LIGHT);
    public static final RegistryObject<Item> FLUORESCENT_LIGHT = RojiuramodModItems.block(RojiuramodModBlocks.FLUORESCENT_LIGHT);
    public static final RegistryObject<Item> ICE_CANDY_BOX = RojiuramodModItems.block(RojiuramodModBlocks.ICE_CANDY_BOX);
    public static final RegistryObject<Item> RECYCLING_BASKET = RojiuramodModItems.block(RojiuramodModBlocks.RECYCLING_BASKET);
    public static final RegistryObject<Item> TRICYCLE = RojiuramodModItems.block(RojiuramodModBlocks.TRICYCLE);
    public static final RegistryObject<Item> POSTAL_POST = RojiuramodModItems.block(RojiuramodModBlocks.POSTAL_POST);
    public static final RegistryObject<Item> BEACH_PARASOL_BLUE = RojiuramodModItems.block(RojiuramodModBlocks.BEACH_PARASOL_BLUE);
    public static final RegistryObject<Item> LOTUS_POT = RojiuramodModItems.block(RojiuramodModBlocks.LOTUS_POT);
    public static final RegistryObject<Item> FIRE_EXTINGUISHER = RojiuramodModItems.block(RojiuramodModBlocks.FIRE_EXTINGUISHER);
    public static final RegistryObject<Item> WELCOME_MAT = RojiuramodModItems.block(RojiuramodModBlocks.WELCOME_MAT);
    public static final RegistryObject<Item> SEPPING_STONE = RojiuramodModItems.block(RojiuramodModBlocks.SEPPING_STONE);
    public static final RegistryObject<Item> ROJIURA_NEON = RojiuramodModItems.block(RojiuramodModBlocks.ROJIURA_NEON);
    public static final RegistryObject<Item> STANDING_SIGN_BOARD = RojiuramodModItems.block(RojiuramodModBlocks.STANDING_SIGN_BOARD);
    public static final RegistryObject<Item> SIGN_BOARD_WALL_S = RojiuramodModItems.block(RojiuramodModBlocks.SIGN_BOARD_WALL_S);
    public static final RegistryObject<Item> SIGN_BOARD_WALL_L = RojiuramodModItems.block(RojiuramodModBlocks.SIGN_BOARD_WALL_L);
    public static final RegistryObject<Item> INSECTS = RojiuramodModItems.block(RojiuramodModBlocks.INSECTS);
    public static final RegistryObject<Item> AWNING_TENT_GREEN = RojiuramodModItems.block(RojiuramodModBlocks.AWNING_TENT_GREEN);
    public static final RegistryObject<Item> AWNING_TENT_RED = RojiuramodModItems.block(RojiuramodModBlocks.AWNING_TENT_RED);
    public static final RegistryObject<Item> AWNING_TENT_WHITE = RojiuramodModItems.block(RojiuramodModBlocks.AWNING_TENT_WHITE);
    public static final RegistryObject<Item> AWNING_TENT_YELLOW = RojiuramodModItems.block(RojiuramodModBlocks.AWNING_TENT_YELLOW);
    public static final RegistryObject<Item> ASPHALT_LAYER_DRY_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.ASPHALT_LAYER_DRY_BLOCK);
    public static final RegistryObject<Item> ASPHALT_LAYER_LINE_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.ASPHALT_LAYER_LINE_BLOCK);
    public static final RegistryObject<Item> ASPHALT_LAYER_WHITE_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.ASPHALT_LAYER_WHITE_BLOCK);
    public static final RegistryObject<Item> ASPHALT_LAYER_CRACK_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.ASPHALT_LAYER_CRACK_BLOCK);
    public static final RegistryObject<Item> ASPHALT_LAYER_HOLE_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.ASPHALT_LAYER_HOLE_BLOCK);
    public static final RegistryObject<Item> ASPHALT_LAYER_WET_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.ASPHALT_LAYER_WET_BLOCK);
    public static final RegistryObject<Item> MANHOLE_CLIMBING = RojiuramodModItems.block(RojiuramodModBlocks.MANHOLE_CLIMBING);
    public static final RegistryObject<Item> CONCRETE_ARCH_UP = RojiuramodModItems.block(RojiuramodModBlocks.CONCRETE_ARCH_UP);
    public static final RegistryObject<Item> CONCRETE_ARCH_DOWN = RojiuramodModItems.block(RojiuramodModBlocks.CONCRETE_ARCH_DOWN);
    public static final RegistryObject<Item> CONCRETE_ARCH_VARTICAL = RojiuramodModItems.block(RojiuramodModBlocks.CONCRETE_ARCH_VARTICAL);
    public static final RegistryObject<Item> WOOD_FLOOR_RED_SLAB = RojiuramodModItems.block(RojiuramodModBlocks.WOOD_FLOOR_RED_SLAB);
    public static final RegistryObject<Item> WOOD_FLOOR_ORANGE_BROWN_SLAB = RojiuramodModItems.block(RojiuramodModBlocks.WOOD_FLOOR_ORANGE_BROWN_SLAB);
    public static final RegistryObject<Item> WOOD_FLOOR_LIGHT_BROWN_SLAB = RojiuramodModItems.block(RojiuramodModBlocks.WOOD_FLOOR_LIGHT_BROWN_SLAB);
    public static final RegistryObject<Item> WOOD_FLOOR_BROWN_SLAB = RojiuramodModItems.block(RojiuramodModBlocks.WOOD_FLOOR_BROWN_SLAB);
    public static final RegistryObject<Item> WOOD_FLOOR_DARK_BROWN_SLAB = RojiuramodModItems.block(RojiuramodModBlocks.WOOD_FLOOR_DARK_BROWN_SLAB);
    public static final RegistryObject<Item> PLY_WOOD_ORANGE_BROWN_SLAB = RojiuramodModItems.block(RojiuramodModBlocks.PLY_WOOD_ORANGE_BROWN_SLAB);
    public static final RegistryObject<Item> PLY_WOOD_LIGHT_BROWN_SLAB = RojiuramodModItems.block(RojiuramodModBlocks.PLY_WOOD_LIGHT_BROWN_SLAB);
    public static final RegistryObject<Item> PLY_WOOD_BROWN_SLAB = RojiuramodModItems.block(RojiuramodModBlocks.PLY_WOOD_BROWN_SLAB);
    public static final RegistryObject<Item> PLY_WOOD_DARK_BROWN_SLAB = RojiuramodModItems.block(RojiuramodModBlocks.PLY_WOOD_DARK_BROWN_SLAB);
    public static final RegistryObject<Item> PLY_WOOD_RED_SLAB = RojiuramodModItems.block(RojiuramodModBlocks.PLY_WOOD_RED_SLAB);
    public static final RegistryObject<Item> STUUCO_WOOD_ORANGE_BROWN_SLAB = RojiuramodModItems.block(RojiuramodModBlocks.STUUCO_WOOD_ORANGE_BROWN_SLAB);
    public static final RegistryObject<Item> STUUCO_WOOD_LIGHT_BROWN_SLAB = RojiuramodModItems.block(RojiuramodModBlocks.STUUCO_WOOD_LIGHT_BROWN_SLAB);
    public static final RegistryObject<Item> STUUCO_WOOD_BROWN_SLAB = RojiuramodModItems.block(RojiuramodModBlocks.STUUCO_WOOD_BROWN_SLAB);
    public static final RegistryObject<Item> STUUCO_WOOD_DARK_SLAB = RojiuramodModItems.block(RojiuramodModBlocks.STUUCO_WOOD_DARK_SLAB);
    public static final RegistryObject<Item> STUUCO_WOOD_RED_SLAB = RojiuramodModItems.block(RojiuramodModBlocks.STUUCO_WOOD_RED_SLAB);
    public static final RegistryObject<Item> TATAMI_YELLWO_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.TATAMI_YELLWO_BLOCK);
    public static final RegistryObject<Item> TATAMI_GREEN_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.TATAMI_GREEN_BLOCK);
    public static final RegistryObject<Item> MORTAR_WHITE_SLAB = RojiuramodModItems.block(RojiuramodModBlocks.MORTAR_WHITE_SLAB);
    public static final RegistryObject<Item> MORTAR_YELLOW_SLAB = RojiuramodModItems.block(RojiuramodModBlocks.MORTAR_YELLOW_SLAB);
    public static final RegistryObject<Item> MORTAR_ORANGE_SLAB = RojiuramodModItems.block(RojiuramodModBlocks.MORTAR_ORANGE_SLAB);
    public static final RegistryObject<Item> MORTAR_LIGHT_BLUE_SLAB = RojiuramodModItems.block(RojiuramodModBlocks.MORTAR_LIGHT_BLUE_SLAB);
    public static final RegistryObject<Item> MORTAR_GRAY_SLAB = RojiuramodModItems.block(RojiuramodModBlocks.MORTAR_GRAY_SLAB);
    public static final RegistryObject<Item> MORTAR_GREEN_SLAB = RojiuramodModItems.block(RojiuramodModBlocks.MORTAR_GREEN_SLAB);
    public static final RegistryObject<Item> MORTAR_CREAM_SLAB = RojiuramodModItems.block(RojiuramodModBlocks.MORTAR_CREAM_SLAB);
    public static final RegistryObject<Item> MODERN_BRICK_WHITE_SLAB = RojiuramodModItems.block(RojiuramodModBlocks.MODERN_BRICK_WHITE_SLAB);
    public static final RegistryObject<Item> MODERN_BRICK_YELLOW_SLAB = RojiuramodModItems.block(RojiuramodModBlocks.MODERN_BRICK_YELLOW_SLAB);
    public static final RegistryObject<Item> MODERN_BRICK_GREEN_SLAB = RojiuramodModItems.block(RojiuramodModBlocks.MODERN_BRICK_GREEN_SLAB);
    public static final RegistryObject<Item> MODERN_BRICK_ORANGE_SLAB = RojiuramodModItems.block(RojiuramodModBlocks.MODERN_BRICK_ORANGE_SLAB);
    public static final RegistryObject<Item> MODERN_BRICK_BLUE_SLAB = RojiuramodModItems.block(RojiuramodModBlocks.MODERN_BRICK_BLUE_SLAB);
    public static final RegistryObject<Item> MODERN_BRICK_GRAY_SLAB = RojiuramodModItems.block(RojiuramodModBlocks.MODERN_BRICK_GRAY_SLAB);
    public static final RegistryObject<Item> MODERN_BRICK_PINK_SLAB = RojiuramodModItems.block(RojiuramodModBlocks.MODERN_BRICK_PINK_SLAB);
    public static final RegistryObject<Item> MODERN_BRICK_CREAM_SLAB = RojiuramodModItems.block(RojiuramodModBlocks.MODERN_BRICK_CREAM_SLAB);
    public static final RegistryObject<Item> MODERN_TILE_WHITE_SLAB = RojiuramodModItems.block(RojiuramodModBlocks.MODERN_TILE_WHITE_SLAB);
    public static final RegistryObject<Item> MODERN_TILE_YELLOW_SLAB = RojiuramodModItems.block(RojiuramodModBlocks.MODERN_TILE_YELLOW_SLAB);
    public static final RegistryObject<Item> MODERN_TILE_ORANGE_SLAB = RojiuramodModItems.block(RojiuramodModBlocks.MODERN_TILE_ORANGE_SLAB);
    public static final RegistryObject<Item> MODERN_TILE_BLUE_SLAB = RojiuramodModItems.block(RojiuramodModBlocks.MODERN_TILE_BLUE_SLAB);
    public static final RegistryObject<Item> MODERN_TILE_GRAY_SLAB = RojiuramodModItems.block(RojiuramodModBlocks.MODERN_TILE_GRAY_SLAB);
    public static final RegistryObject<Item> MODERN_TILE_PINK_SLAB = RojiuramodModItems.block(RojiuramodModBlocks.MODERN_TILE_PINK_SLAB);
    public static final RegistryObject<Item> MODERN_TILE_GREEN_SLAB = RojiuramodModItems.block(RojiuramodModBlocks.MODERN_TILE_GREEN_SLAB);
    public static final RegistryObject<Item> MODERN_TILE_CREAM_SLAB = RojiuramodModItems.block(RojiuramodModBlocks.MODERN_TILE_CREAM_SLAB);
    public static final RegistryObject<Item> TOTAN_S_BLUE_SLAB = RojiuramodModItems.block(RojiuramodModBlocks.TOTAN_S_BLUE_SLAB);
    public static final RegistryObject<Item> TOTAN_S_WHITE_SLAB = RojiuramodModItems.block(RojiuramodModBlocks.TOTAN_S_WHITE_SLAB);
    public static final RegistryObject<Item> TOTAN_S_PINK_SLAB = RojiuramodModItems.block(RojiuramodModBlocks.TOTAN_S_PINK_SLAB);
    public static final RegistryObject<Item> TOTAN_S_YELLOW_SLAB = RojiuramodModItems.block(RojiuramodModBlocks.TOTAN_S_YELLOW_SLAB);
    public static final RegistryObject<Item> TOTAN_S_BROWN_SLAB = RojiuramodModItems.block(RojiuramodModBlocks.TOTAN_S_BROWN_SLAB);
    public static final RegistryObject<Item> TOTAN_S_GRAY_SLAB = RojiuramodModItems.block(RojiuramodModBlocks.TOTAN_S_GRAY_SLAB);
    public static final RegistryObject<Item> TOTAN_S_GREEN_SLAB = RojiuramodModItems.block(RojiuramodModBlocks.TOTAN_S_GREEN_SLAB);
    public static final RegistryObject<Item> TOTAN_S_RED_SLAB = RojiuramodModItems.block(RojiuramodModBlocks.TOTAN_S_RED_SLAB);
    public static final RegistryObject<Item> TOTAN_L_BLUE_SLAB = RojiuramodModItems.block(RojiuramodModBlocks.TOTAN_L_BLUE_SLAB);
    public static final RegistryObject<Item> TOTAN_L_WHITE_SLAB = RojiuramodModItems.block(RojiuramodModBlocks.TOTAN_L_WHITE_SLAB);
    public static final RegistryObject<Item> TOTAN_L_PINK_SLAB = RojiuramodModItems.block(RojiuramodModBlocks.TOTAN_L_PINK_SLAB);
    public static final RegistryObject<Item> TOTAN_L_YELLOW_SLAB = RojiuramodModItems.block(RojiuramodModBlocks.TOTAN_L_YELLOW_SLAB);
    public static final RegistryObject<Item> TOTAN_L_BROWN_SLAB = RojiuramodModItems.block(RojiuramodModBlocks.TOTAN_L_BROWN_SLAB);
    public static final RegistryObject<Item> TOTAN_L_GRAY_SLAB = RojiuramodModItems.block(RojiuramodModBlocks.TOTAN_L_GRAY_SLAB);
    public static final RegistryObject<Item> TOTAN_L_GREEN_SLAB = RojiuramodModItems.block(RojiuramodModBlocks.TOTAN_L_GREEN_SLAB);
    public static final RegistryObject<Item> TOTAN_L_ORANGE_SLAB = RojiuramodModItems.block(RojiuramodModBlocks.TOTAN_L_ORANGE_SLAB);
    public static final RegistryObject<Item> MORTAR_PINK_SLAB = RojiuramodModItems.block(RojiuramodModBlocks.MORTAR_PINK_SLAB);
    public static final RegistryObject<Item> KUTUNUGI_ISHI = RojiuramodModItems.block(RojiuramodModBlocks.KUTUNUGI_ISHI);
    public static final RegistryObject<Item> WIND_CHIME = RojiuramodModItems.block(RojiuramodModBlocks.WIND_CHIME);
    public static final RegistryObject<Item> MOSQUITO_COIL = RojiuramodModItems.block(RojiuramodModBlocks.MOSQUITO_COIL);
    public static final RegistryObject<Item> LOW_TREE_LEAF_LIGHTGREEN = RojiuramodModItems.block(RojiuramodModBlocks.LOW_TREE_LEAF_LIGHTGREEN);
    public static final RegistryObject<Item> LOW_TREE_LEAF_DEEPGREEN = RojiuramodModItems.block(RojiuramodModBlocks.LOW_TREE_LEAF_DEEPGREEN);
    public static final RegistryObject<Item> BAM_BOO = RojiuramodModItems.block(RojiuramodModBlocks.BAM_BOO);
    public static final RegistryObject<Item> AJISAI = RojiuramodModItems.block(RojiuramodModBlocks.AJISAI);
    public static final RegistryObject<Item> HIGANBANA = RojiuramodModItems.block(RojiuramodModBlocks.HIGANBANA);
    public static final RegistryObject<Item> SUSUKI = RojiuramodModItems.block(RojiuramodModBlocks.SUSUKI);
    public static final RegistryObject<Item> TUBAKI = RojiuramodModItems.block(RojiuramodModBlocks.TUBAKI);
    public static final RegistryObject<Item> CAPSEL_TOY_MACHINE = RojiuramodModItems.block(RojiuramodModBlocks.CAPSEL_TOY_MACHINE);
    public static final RegistryObject<Item> CAPSEL_TOY_MACHINE_2 = RojiuramodModItems.block(RojiuramodModBlocks.CAPSEL_TOY_MACHINE_2);
    public static final RegistryObject<Item> CAPSEL_TOY_MACHINE_3 = RojiuramodModItems.block(RojiuramodModBlocks.CAPSEL_TOY_MACHINE_3);
    public static final RegistryObject<Item> CAPSEL_TOY_MACHINE_4 = RojiuramodModItems.block(RojiuramodModBlocks.CAPSEL_TOY_MACHINE_4);
    public static final RegistryObject<Item> BARRICADE = RojiuramodModItems.block(RojiuramodModBlocks.BARRICADE);
    public static final RegistryObject<Item> PARK_BARRICADE = RojiuramodModItems.block(RojiuramodModBlocks.PARK_BARRICADE);
    public static final RegistryObject<Item> ROAD_CONE = RojiuramodModItems.block(RojiuramodModBlocks.ROAD_CONE);
    public static final RegistryObject<Item> ROAD_CONE_BAR = RojiuramodModItems.block(RojiuramodModBlocks.ROAD_CONE_BAR);
    public static final RegistryObject<Item> INVISIBLE_LIGHT = REGISTRY.register("invisible_light", () -> new LnvisibleLightItem());
    public static final RegistryObject<Item> PUBLIC_TELEPHONE = RojiuramodModItems.block(RojiuramodModBlocks.PUBLIC_TELEPHONE);
    public static final RegistryObject<Item> PUBLIC_TELEPHONE_TABLE = RojiuramodModItems.block(RojiuramodModBlocks.PUBLIC_TELEPHONE_TABLE);
    public static final RegistryObject<Item> ELECTRIC_FAN = RojiuramodModItems.block(RojiuramodModBlocks.ELECTRIC_FAN);
    public static final RegistryObject<Item> JIZOU = RojiuramodModItems.block(RojiuramodModBlocks.JIZOU);
    public static final RegistryObject<Item> SEKIZOU = RojiuramodModItems.block(RojiuramodModBlocks.SEKIZOU);
    public static final RegistryObject<Item> ICE_CANDY_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.ICE_CANDY_BLOCK);
    public static final RegistryObject<Item> ITEM_TRASH_BAGS = RojiuramodModItems.block(RojiuramodModBlocks.ITEM_TRASH_BAGS);
    public static final RegistryObject<Item> CARD_BOARD_BED_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.CARD_BOARD_BED_BLOCK);
    public static final RegistryObject<Item> VENDINGMACHINEBLOCK = RojiuramodModItems.block(RojiuramodModBlocks.VENDINGMACHINEBLOCK);
    public static final RegistryObject<Item> VENDING_MACHINE = REGISTRY.register("vending_machine", () -> new VendingMachineItem());
    public static final RegistryObject<Item> BENCH_BLUE = REGISTRY.register("bench_blue", () -> new BenchItem());
    public static final RegistryObject<Item> BENCH_RED = REGISTRY.register("bench_red", () -> new BenchRedItem());
    public static final RegistryObject<Item> BENCH_WOOD = REGISTRY.register("bench_wood", () -> new BenchWoodItem());
    public static final RegistryObject<Item> GRAVITY_STICK = REGISTRY.register("gravity_stick", () -> new GravityStickItem());
    public static final RegistryObject<Item> BENCH_BLUE_BLCOK = RojiuramodModItems.block(RojiuramodModBlocks.BENCH_BLUE_BLCOK);
    public static final RegistryObject<Item> BENCH_RED_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.BENCH_RED_BLOCK);
    public static final RegistryObject<Item> BENCH_WOOD_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.BENCH_WOOD_BLOCK);
    public static final RegistryObject<Item> COIN = REGISTRY.register("coin", () -> new CoinItem());
    public static final RegistryObject<Item> CANS = REGISTRY.register("cans", () -> new CansItem());
    public static final RegistryObject<Item> CANS_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.CANS_BLOCK);
    public static final RegistryObject<Item> INVISIBLE_LIGHT_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.INVISIBLE_LIGHT_BLOCK);
    public static final RegistryObject<Item> COIN_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.COIN_BLOCK);
    public static final RegistryObject<Item> BEER = REGISTRY.register("beer", () -> new Beer1Item());
    public static final RegistryObject<Item> ICE_CANDY = REGISTRY.register("ice_candy", () -> new IceCandy1Item());
    public static final RegistryObject<Item> INVISIBLE_LIGHT_4 = REGISTRY.register("invisible_light_4", () -> new InvisibleLight4Item());
    public static final RegistryObject<Item> INVISIBLE_LIGHT_8 = REGISTRY.register("invisible_light_8", () -> new InvisibleLight8Item());
    public static final RegistryObject<Item> INVISIBLE_LIGHT_12 = REGISTRY.register("invisible_light_12", () -> new InvisibleLight12Item());
    public static final RegistryObject<Item> OUT_DOOR_UNIT = RojiuramodModItems.block(RojiuramodModBlocks.OUT_DOOR_UNIT);
    public static final RegistryObject<Item> BEACH_ROCK_STAIR = RojiuramodModItems.block(RojiuramodModBlocks.BEACH_ROCK_STAIR);
    public static final RegistryObject<Item> TATAMI_YELLOW = REGISTRY.register("tatami_yellow", () -> new TatamiYellowItem());
    public static final RegistryObject<Item> TATAMI_GREEN = REGISTRY.register("tatami_green", () -> new TatamiGreen1Item());
    public static final RegistryObject<Item> CARD_BOARD_BED_1 = REGISTRY.register("card_board_bed_1", () -> new CardBoardBed1Item());
    public static final RegistryObject<Item> ASPHALT_LAYER_DRY = REGISTRY.register("asphalt_layer_dry", () -> new AsphaltLayerDry1Item());
    public static final RegistryObject<Item> ASPHALT_LAYER_LINE = REGISTRY.register("asphalt_layer_line", () -> new AsphaltLayerLine1Item());
    public static final RegistryObject<Item> ASPHALT_LAYER_WHITE = REGISTRY.register("asphalt_layer_white", () -> new AsphaltLayerWhite1Item());
    public static final RegistryObject<Item> ASPHALT_LAYER_CRACK = REGISTRY.register("asphalt_layer_crack", () -> new AsphaltLayerCrack1Item());
    public static final RegistryObject<Item> ASPHALT_LAYER_HOLE = REGISTRY.register("asphalt_layer_hole", () -> new AsphaltLayerHole1Item());
    public static final RegistryObject<Item> ASPHALT_LAYER_WET = REGISTRY.register("asphalt_layer_wet", () -> new AsphaltLayerWet1Item());
    public static final RegistryObject<Item> POSTERS = RojiuramodModItems.block(RojiuramodModBlocks.POSTERS);
    public static final RegistryObject<Item> POSTER_1X1 = REGISTRY.register("poster_1x1", () -> new Poster1X1Item());
    public static final RegistryObject<Item> POSTER_1X2 = REGISTRY.register("poster_1x2", () -> new Poster1X2Item());
    public static final RegistryObject<Item> POSTER_2X1 = REGISTRY.register("poster_2x1", () -> new Poster2X1Item());
    public static final RegistryObject<Item> POSTER_2X2 = REGISTRY.register("poster_2x2", () -> new Poster2X2Item());
    public static final RegistryObject<Item> POSTER_2X3 = REGISTRY.register("poster_2x3", () -> new Poster2X3Item());
    public static final RegistryObject<Item> POSTER_1X4 = REGISTRY.register("poster_1x4", () -> new Poster1X4Item());
    public static final RegistryObject<Item> POSTER_1X5 = REGISTRY.register("poster_1x5", () -> new Poster1X5Item());
    public static final RegistryObject<Item> POSTER_4X4 = REGISTRY.register("poster_4x4", () -> new Poster4X4Item());
    public static final RegistryObject<Item> POSTER_2X6 = REGISTRY.register("poster_2x6", () -> new Poster2X6Item());
    public static final RegistryObject<Item> BEACH_PARASOL_RED = RojiuramodModItems.block(RojiuramodModBlocks.BEACH_PARASOL_RED);
    public static final RegistryObject<Item> BEACH_PARASOL_CYAN = RojiuramodModItems.block(RojiuramodModBlocks.BEACH_PARASOL_CYAN);
    public static final RegistryObject<Item> BEACH_PARASOL_YELLOW = RojiuramodModItems.block(RojiuramodModBlocks.BEACH_PARASOL_YELLOW);
    public static final RegistryObject<Item> BEACH_PARASOL_PINK = RojiuramodModItems.block(RojiuramodModBlocks.BEACH_PARASOL_PINK);
    public static final RegistryObject<Item> BEACH_PARASOL_GREEN = RojiuramodModItems.block(RojiuramodModBlocks.BEACH_PARASOL_GREEN);
    public static final RegistryObject<Item> BEACH_PARASOL_STRIPE_BLUE = RojiuramodModItems.block(RojiuramodModBlocks.BEACH_PARASOL_STRIPE_BLUE);
    public static final RegistryObject<Item> BEACH_PARASOL_STRIPE_RED = RojiuramodModItems.block(RojiuramodModBlocks.BEACH_PARASOL_STRIPE_RED);
    public static final RegistryObject<Item> BEACH_PARASOL_STRIPE_CYAN = RojiuramodModItems.block(RojiuramodModBlocks.BEACH_PARASOL_STRIPE_CYAN);
    public static final RegistryObject<Item> BEACH_PARASOL_STRIPE_YELLOW = RojiuramodModItems.block(RojiuramodModBlocks.BEACH_PARASOL_STRIPE_YELLOW);
    public static final RegistryObject<Item> BEACH_PARASOL_STRIPE_PINK = RojiuramodModItems.block(RojiuramodModBlocks.BEACH_PARASOL_STRIPE_PINK);
    public static final RegistryObject<Item> BEACH_PARASOL_STRIPE_GREEN = RojiuramodModItems.block(RojiuramodModBlocks.BEACH_PARASOL_STRIPE_GREEN);
    public static final RegistryObject<Item> BEACH_PARASOL_CLOTH_WHITE = RojiuramodModItems.block(RojiuramodModBlocks.BEACH_PARASOL_CLOTH_WHITE);
    public static final RegistryObject<Item> BEACH_PARASOL_CLOTH_GREEN = RojiuramodModItems.block(RojiuramodModBlocks.BEACH_PARASOL_CLOTH_GREEN);
    public static final RegistryObject<Item> BEACH_PARASOL_CLOTH_BLACK = RojiuramodModItems.block(RojiuramodModBlocks.BEACH_PARASOL_CLOTH_BLACK);
    public static final RegistryObject<Item> BEACH_PARASOL_CLOTH_BROWN = RojiuramodModItems.block(RojiuramodModBlocks.BEACH_PARASOL_CLOTH_BROWN);
    public static final RegistryObject<Item> PICNIC_SHEET = RojiuramodModItems.block(RojiuramodModBlocks.PICNIC_SHEET);
    public static final RegistryObject<Item> COOLER_BOX = RojiuramodModItems.block(RojiuramodModBlocks.COOLER_BOX);
    public static final RegistryObject<Item> BOLLARD = RojiuramodModItems.block(RojiuramodModBlocks.BOLLARD);
    public static final RegistryObject<Item> FENDER = RojiuramodModItems.block(RojiuramodModBlocks.FENDER);
    public static final RegistryObject<Item> WHEEL_STOP = RojiuramodModItems.block(RojiuramodModBlocks.WHEEL_STOP);
    public static final RegistryObject<Item> PIER = RojiuramodModItems.block(RojiuramodModBlocks.PIER);
    public static final RegistryObject<Item> PIER_PILLAR = RojiuramodModItems.block(RojiuramodModBlocks.PIER_PILLAR);
    public static final RegistryObject<Item> BEACH_SAND_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.BEACH_SAND_BLOCK);
    public static final RegistryObject<Item> BEACH_SAND = REGISTRY.register("beach_sand", () -> new BeachSandItem());
    public static final RegistryObject<Item> SHELL = RojiuramodModItems.block(RojiuramodModBlocks.SHELL);
    public static final RegistryObject<Item> SNAIL = RojiuramodModItems.block(RojiuramodModBlocks.SNAIL);
    public static final RegistryObject<Item> STARFISH = RojiuramodModItems.block(RojiuramodModBlocks.STARFISH);
    public static final RegistryObject<Item> DRIFTWOOD = RojiuramodModItems.block(RojiuramodModBlocks.DRIFTWOOD);
    public static final RegistryObject<Item> SEAWEED = RojiuramodModItems.block(RojiuramodModBlocks.SEAWEED);
    public static final RegistryObject<Item> BUOY_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.BUOY_BLOCK);
    public static final RegistryObject<Item> BUOY = REGISTRY.register("buoy", () -> new BuoyItem());
    public static final RegistryObject<Item> FLOATING_RING = REGISTRY.register("floating_ring", () -> new FloatingRingItem());
    public static final RegistryObject<Item> FAN_COVER = RojiuramodModItems.block(RojiuramodModBlocks.FAN_COVER);
    public static final RegistryObject<Item> LP_GAS_CYLINDER = RojiuramodModItems.block(RojiuramodModBlocks.LP_GAS_CYLINDER);
    public static final RegistryObject<Item> WATER_HEATER = RojiuramodModItems.block(RojiuramodModBlocks.WATER_HEATER);
    public static final RegistryObject<Item> SHUTTER_CASE = RojiuramodModItems.block(RojiuramodModBlocks.SHUTTER_CASE);
    public static final RegistryObject<Item> GUARDRAIL_WHITE = RojiuramodModItems.block(RojiuramodModBlocks.GUARDRAIL_WHITE);
    public static final RegistryObject<Item> CURB = RojiuramodModItems.block(RojiuramodModBlocks.CURB);
    public static final RegistryObject<Item> WOOD_WALL = RojiuramodModItems.block(RojiuramodModBlocks.WOOD_WALL);
    public static final RegistryObject<Item> CONCRETE_WALL = RojiuramodModItems.block(RojiuramodModBlocks.CONCRETE_WALL);
    public static final RegistryObject<Item> CONCRETE_WALL_WINDHOLE = RojiuramodModItems.block(RojiuramodModBlocks.CONCRETE_WALL_WINDHOLE);
    public static final RegistryObject<Item> TOTAN_WALL = RojiuramodModItems.block(RojiuramodModBlocks.TOTAN_WALL);
    public static final RegistryObject<Item> GREEN_FENCE = RojiuramodModItems.block(RojiuramodModBlocks.GREEN_FENCE);
    public static final RegistryObject<Item> GAS_METER = RojiuramodModItems.block(RojiuramodModBlocks.GAS_METER);
    public static final RegistryObject<Item> ENGAWA = RojiuramodModItems.block(RojiuramodModBlocks.ENGAWA);
    public static final RegistryObject<Item> WOOD_TOBUKURO_ORANGE_BROWN = RojiuramodModItems.block(RojiuramodModBlocks.WOOD_TOBUKURO_ORANGE_BROWN);
    public static final RegistryObject<Item> WOOD_TOBUKURO_LIGHT_BROWN = RojiuramodModItems.block(RojiuramodModBlocks.WOOD_TOBUKURO_LIGHT_BROWN);
    public static final RegistryObject<Item> WOOD_TOBUKURO_BROWN = RojiuramodModItems.block(RojiuramodModBlocks.WOOD_TOBUKURO_BROWN);
    public static final RegistryObject<Item> WOOD_TOBUKURO_DARK_BROWN = RojiuramodModItems.block(RojiuramodModBlocks.WOOD_TOBUKURO_DARK_BROWN);
    public static final RegistryObject<Item> WOOD_TOBUKURO_RED = RojiuramodModItems.block(RojiuramodModBlocks.WOOD_TOBUKURO_RED);
    public static final RegistryObject<Item> HISASI = RojiuramodModItems.block(RojiuramodModBlocks.HISASI);
    public static final RegistryObject<Item> WOOD_WINDOW_ORANGE_BROWN = RojiuramodModItems.block(RojiuramodModBlocks.WOOD_WINDOW_ORANGE_BROWN);
    public static final RegistryObject<Item> WOOD_WINDOW_LIGHT_BROWN = RojiuramodModItems.block(RojiuramodModBlocks.WOOD_WINDOW_LIGHT_BROWN);
    public static final RegistryObject<Item> WOOD_WINDOW_BROWN = RojiuramodModItems.block(RojiuramodModBlocks.WOOD_WINDOW_BROWN);
    public static final RegistryObject<Item> WOOD_WINDOW_DARK_BROWN = RojiuramodModItems.block(RojiuramodModBlocks.WOOD_WINDOW_DARK_BROWN);
    public static final RegistryObject<Item> WOOD_WINDOW_RED = RojiuramodModItems.block(RojiuramodModBlocks.WOOD_WINDOW_RED);
    public static final RegistryObject<Item> ALM_WINDOW = RojiuramodModItems.block(RojiuramodModBlocks.ALM_WINDOW);
    public static final RegistryObject<Item> WOOD_PILLAR_ORANGE_BROWN = RojiuramodModItems.block(RojiuramodModBlocks.WOOD_PILLAR_ORANGE_BROWN);
    public static final RegistryObject<Item> WOOD_PILLAR_LIGHT_BROWN = RojiuramodModItems.block(RojiuramodModBlocks.WOOD_PILLAR_LIGHT_BROWN);
    public static final RegistryObject<Item> WOOD_PILLAR_BROWN = RojiuramodModItems.block(RojiuramodModBlocks.WOOD_PILLAR_BROWN);
    public static final RegistryObject<Item> WOOD_PILLAR_DARK_BROWN = RojiuramodModItems.block(RojiuramodModBlocks.WOOD_PILLAR_DARK_BROWN);
    public static final RegistryObject<Item> WOOD_PILLAR_RED = RojiuramodModItems.block(RojiuramodModBlocks.WOOD_PILLAR_RED);
    public static final RegistryObject<Item> METAL_PILLAR_WHITE = RojiuramodModItems.block(RojiuramodModBlocks.METAL_PILLAR_WHITE);
    public static final RegistryObject<Item> METAL_PILLAR_BROWN = RojiuramodModItems.block(RojiuramodModBlocks.METAL_PILLAR_BROWN);
    public static final RegistryObject<Item> METAL_PILLAR_BLACK = RojiuramodModItems.block(RojiuramodModBlocks.METAL_PILLAR_BLACK);
    public static final RegistryObject<Item> METAL_PILLAR_YELLOW = RojiuramodModItems.block(RojiuramodModBlocks.METAL_PILLAR_YELLOW);
    public static final RegistryObject<Item> METAL_PILLAR_GREEN = RojiuramodModItems.block(RojiuramodModBlocks.METAL_PILLAR_GREEN);
    public static final RegistryObject<Item> DRAIN_PIPE = RojiuramodModItems.block(RojiuramodModBlocks.DRAIN_PIPE);
    public static final RegistryObject<Item> METAL_STAIR_WHITE = RojiuramodModItems.block(RojiuramodModBlocks.METAL_STAIR_WHITE);
    public static final RegistryObject<Item> METAL_STAIR_BROWN = RojiuramodModItems.block(RojiuramodModBlocks.METAL_STAIR_BROWN);
    public static final RegistryObject<Item> METAL_STAIR_BLACK = RojiuramodModItems.block(RojiuramodModBlocks.METAL_STAIR_BLACK);
    public static final RegistryObject<Item> METAL_STAIR_YELLOW = RojiuramodModItems.block(RojiuramodModBlocks.METAL_STAIR_YELLOW);
    public static final RegistryObject<Item> METAL_STAIR_GREEN = RojiuramodModItems.block(RojiuramodModBlocks.METAL_STAIR_GREEN);
    public static final RegistryObject<Item> METAL_FENCE_WHITE = RojiuramodModItems.block(RojiuramodModBlocks.METAL_FENCE_WHITE);
    public static final RegistryObject<Item> METAL_FENCE_BROWN = RojiuramodModItems.block(RojiuramodModBlocks.METAL_FENCE_BROWN);
    public static final RegistryObject<Item> METAL_FENCE_BLACK = RojiuramodModItems.block(RojiuramodModBlocks.METAL_FENCE_BLACK);
    public static final RegistryObject<Item> METAL_FENCE_YELLOW = RojiuramodModItems.block(RojiuramodModBlocks.METAL_FENCE_YELLOW);
    public static final RegistryObject<Item> METAL_FENCE_GREEN = RojiuramodModItems.block(RojiuramodModBlocks.METAL_FENCE_GREEN);
    public static final RegistryObject<Item> METAL_FLOOR_WHITE = RojiuramodModItems.block(RojiuramodModBlocks.METAL_FLOOR_WHITE);
    public static final RegistryObject<Item> METAL_FLOOR_BROWN = RojiuramodModItems.block(RojiuramodModBlocks.METAL_FLOOR_BROWN);
    public static final RegistryObject<Item> METAL_FLOOR_BLACK = RojiuramodModItems.block(RojiuramodModBlocks.METAL_FLOOR_BLACK);
    public static final RegistryObject<Item> METAL_FLOOR_YELLOW = RojiuramodModItems.block(RojiuramodModBlocks.METAL_FLOOR_YELLOW);
    public static final RegistryObject<Item> METAL_FLOOR_GREEN = RojiuramodModItems.block(RojiuramodModBlocks.METAL_FLOOR_GREEN);
    public static final RegistryObject<Item> OLD_CONCRETE_STAIR = RojiuramodModItems.block(RojiuramodModBlocks.OLD_CONCRETE_STAIR);
    public static final RegistryObject<Item> OUTDOOR_SPOTLIGHT = RojiuramodModItems.block(RojiuramodModBlocks.OUTDOOR_SPOTLIGHT);
    public static final RegistryObject<Item> ROOF_SIGNBOARD_BASE = RojiuramodModItems.block(RojiuramodModBlocks.ROOF_SIGNBOARD_BASE);
    public static final RegistryObject<Item> UTILITY_POLE_BOTTOM = RojiuramodModItems.block(RojiuramodModBlocks.UTILITY_POLE_BOTTOM);
    public static final RegistryObject<Item> UTILITY_POLE_MIDDLE = RojiuramodModItems.block(RojiuramodModBlocks.UTILITY_POLE_MIDDLE);
    public static final RegistryObject<Item> UTILITY_POLE_TOP = RojiuramodModItems.block(RojiuramodModBlocks.UTILITY_POLE_TOP);
    public static final RegistryObject<Item> ELECTRICAL_WIRE = RojiuramodModItems.block(RojiuramodModBlocks.ELECTRICAL_WIRE);
    public static final RegistryObject<Item> UTILITY_POLE_PART = RojiuramodModItems.block(RojiuramodModBlocks.UTILITY_POLE_PART);
    public static final RegistryObject<Item> UTILITY_POLE_SIGNS = RojiuramodModItems.block(RojiuramodModBlocks.UTILITY_POLE_SIGNS);
    public static final RegistryObject<Item> UTILITY_POLE_LIGHT = RojiuramodModItems.block(RojiuramodModBlocks.UTILITY_POLE_LIGHT);
    public static final RegistryObject<Item> RANMA_ORANGE_BROWN = RojiuramodModItems.block(RojiuramodModBlocks.RANMA_ORANGE_BROWN);
    public static final RegistryObject<Item> RANMA_LIGHT_BROWN = RojiuramodModItems.block(RojiuramodModBlocks.RANMA_LIGHT_BROWN);
    public static final RegistryObject<Item> RANMA_BROWN = RojiuramodModItems.block(RojiuramodModBlocks.RANMA_BROWN);
    public static final RegistryObject<Item> ELECTRICITY_METER = RojiuramodModItems.block(RojiuramodModBlocks.ELECTRICITY_METER);
    public static final RegistryObject<Item> MONOHOSI = RojiuramodModItems.block(RojiuramodModBlocks.MONOHOSI);
    public static final RegistryObject<Item> MONOHOSI_BAR = RojiuramodModItems.block(RojiuramodModBlocks.MONOHOSI_BAR);
    public static final RegistryObject<Item> BUILDING_MAILBOX = RojiuramodModItems.block(RojiuramodModBlocks.BUILDING_MAILBOX);
    public static final RegistryObject<Item> TOTAN_ROOF_BLUE = REGISTRY.register("totan_roof_blue", () -> new TotanRoofBlueItem());
    public static final RegistryObject<Item> TOTAN_ROOF_BLUE_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.TOTAN_ROOF_BLUE_BLOCK);
    public static final RegistryObject<Item> TOTAN_ROOF_RED = REGISTRY.register("totan_roof_red", () -> new TotanRoofRedItem());
    public static final RegistryObject<Item> TOTAN_ROOF_RED_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.TOTAN_ROOF_RED_BLOCK);
    public static final RegistryObject<Item> TOTAN_ROOF_GRAY = REGISTRY.register("totan_roof_gray", () -> new TotanRoofGrayItem());
    public static final RegistryObject<Item> TOTAN_ROOF_GRAY_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.TOTAN_ROOF_GRAY_BLOCK);
    public static final RegistryObject<Item> KAWARA_BLACK = REGISTRY.register("kawara_black", () -> new KawaraBlackItem());
    public static final RegistryObject<Item> KAWARA_BLACK_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.KAWARA_BLACK_BLOCK);
    public static final RegistryObject<Item> KAWARA_GRAY = REGISTRY.register("kawara_gray", () -> new KawaraGrayItem());
    public static final RegistryObject<Item> KAWARA_GRAY_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.KAWARA_GRAY_BLOCK);
    public static final RegistryObject<Item> KAWARA_BLUE = REGISTRY.register("kawara_blue", () -> new KawaraBlueItem());
    public static final RegistryObject<Item> KAWARA_BLUE_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.KAWARA_BLUE_BLOCK);
    public static final RegistryObject<Item> KAWARA_GREEN = REGISTRY.register("kawara_green", () -> new KawaraGreenItem());
    public static final RegistryObject<Item> KAWARA_GREEN_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.KAWARA_GREEN_BLOCK);
    public static final RegistryObject<Item> KAWARA_ORANGE = REGISTRY.register("kawara_orange", () -> new KawaraOrangeItem());
    public static final RegistryObject<Item> KAWARA_ORANGE_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.KAWARA_ORANGE_BLOCK);
    public static final RegistryObject<Item> KAWARA_ODD_BLACK = REGISTRY.register("kawara_odd_black", () -> new KawaraOddBlackItem());
    public static final RegistryObject<Item> KAWARA_ODD_BLACK_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.KAWARA_ODD_BLACK_BLOCK);
    public static final RegistryObject<Item> KAWARA_ODD_GRAY = REGISTRY.register("kawara_odd_gray", () -> new KawaraOddGrayItem());
    public static final RegistryObject<Item> KAWARA_ODD_GRAY_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.KAWARA_ODD_GRAY_BLOCK);
    public static final RegistryObject<Item> KAWARA_ODD_BLUE = REGISTRY.register("kawara_odd_blue", () -> new KawaraOddBlueItem());
    public static final RegistryObject<Item> KAWARA_ODD_BLUE_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.KAWARA_ODD_BLUE_BLOCK);
    public static final RegistryObject<Item> KAWARA_ODD_GREEN = REGISTRY.register("kawara_odd_green", () -> new KawaraOddGreenItem());
    public static final RegistryObject<Item> KAWARA_ODD_GREEN_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.KAWARA_ODD_GREEN_BLOCK);
    public static final RegistryObject<Item> KAWARA_ODD_ORANGE = REGISTRY.register("kawara_odd_orange", () -> new KawaraOddOrangeItem());
    public static final RegistryObject<Item> KAWARA_ODD_ORANGE_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.KAWARA_ODD_ORANGE_BLOCK);
    public static final RegistryObject<Item> METAL_DOOR_WHITE = REGISTRY.register("metal_door_white", () -> new DoorMetalWhiteItem());
    public static final RegistryObject<Item> METAL_DOOR_WHITE_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.METAL_DOOR_WHITE_BLOCK);
    public static final RegistryObject<Item> METAL_DOOR_YELLOW = REGISTRY.register("metal_door_yellow", () -> new DoormetalYellowItem());
    public static final RegistryObject<Item> METAL_DOOR_YELLOW_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.METAL_DOOR_YELLOW_BLOCK);
    public static final RegistryObject<Item> METAL_DOOR_GREEN = REGISTRY.register("metal_door_green", () -> new DoorMetalGreenItem());
    public static final RegistryObject<Item> METAL_DOOR_GREEN_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.METAL_DOOR_GREEN_BLOCK);
    public static final RegistryObject<Item> METAL_DOOR_BROWN = REGISTRY.register("metal_door_brown", () -> new DoorMetalBrownItem());
    public static final RegistryObject<Item> METAL_DOOR_BROWN_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.METAL_DOOR_BROWN_BLOCK);
    public static final RegistryObject<Item> METAL_DOOR_BLACK = REGISTRY.register("metal_door_black", () -> new DoorMetalBlackItem());
    public static final RegistryObject<Item> METAL_DOOR_BLACK_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.METAL_DOOR_BLACK_BLOCK);
    public static final RegistryObject<Item> OLD_DOOR = REGISTRY.register("old_door", () -> new OldDoorItem());
    public static final RegistryObject<Item> OLD_DOOR_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.OLD_DOOR_BLOCK);
    public static final RegistryObject<Item> METAL_DOOR_WINDOW_WHITE = REGISTRY.register("metal_door_window_white", () -> new MetalDoorWindowWhiteItem());
    public static final RegistryObject<Item> METAL_DOOR_WINDOW_WHITE_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.METAL_DOOR_WINDOW_WHITE_BLOCK);
    public static final RegistryObject<Item> METAL_DOOR_WINDOW_YELLOW = REGISTRY.register("metal_door_window_yellow", () -> new MetalDoorWindowYellowItem());
    public static final RegistryObject<Item> METAL_DOOR_WINDOW_YELLOW_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.METAL_DOOR_WINDOW_YELLOW_BLOCK);
    public static final RegistryObject<Item> METAL_DOOR_WINDOW_GREEN = REGISTRY.register("metal_door_window_green", () -> new MetalDoorWindowGreenItem());
    public static final RegistryObject<Item> METAL_DOOR_WINDOW_GREEN_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.METAL_DOOR_WINDOW_GREEN_BLOCK);
    public static final RegistryObject<Item> METAL_DOOR_WINDOW_BROWN = REGISTRY.register("metal_door_window_brown", () -> new MetalDoorWindowBrownItem());
    public static final RegistryObject<Item> METAL_DOOR_WINDOW_BROWN_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.METAL_DOOR_WINDOW_BROWN_BLOCK);
    public static final RegistryObject<Item> METAL_DOOR_WINDOW_BLACK = REGISTRY.register("metal_door_window_black", () -> new MetalDoorWindowBlackItem());
    public static final RegistryObject<Item> METAL_DOOR_WINDOW_BLACK_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.METAL_DOOR_WINDOW_BLACK_BLOCK);
    public static final RegistryObject<Item> METAL_DOOR_TALL_WHITE = REGISTRY.register("metal_door_tall_white", () -> new MetalDoorTallWhiteItem());
    public static final RegistryObject<Item> METAL_DOOR_TALL_WHITE_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.METAL_DOOR_TALL_WHITE_BLOCK);
    public static final RegistryObject<Item> METAL_DOOR_TALL_YELLOW = REGISTRY.register("metal_door_tall_yellow", () -> new MetalDoorTallYellowItem());
    public static final RegistryObject<Item> METAL_DOOR_TALL_YELLOW_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.METAL_DOOR_TALL_YELLOW_BLOCK);
    public static final RegistryObject<Item> METAL_DOOR_TALL_GREEN = REGISTRY.register("metal_door_tall_green", () -> new MetalDoorTallGreenItem());
    public static final RegistryObject<Item> METAL_DOOR_TALL_GREEN_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.METAL_DOOR_TALL_GREEN_BLOCK);
    public static final RegistryObject<Item> METAL_DOOR_TALL_BROWN = REGISTRY.register("metal_door_tall_brown", () -> new MetalDoorTallBorwnItem());
    public static final RegistryObject<Item> METAL_DOOR_TALL_BROWN_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.METAL_DOOR_TALL_BROWN_BLOCK);
    public static final RegistryObject<Item> METAL_DOOR_TALL_BLACK = REGISTRY.register("metal_door_tall_black", () -> new MetalDoorTallBlackItem());
    public static final RegistryObject<Item> METAL_DOOR_TALL_BLACK_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.METAL_DOOR_TALL_BLACK_BLOCK);
    public static final RegistryObject<Item> METAL_DOOR_TALL_WINDOW_WHITE = REGISTRY.register("metal_door_tall_window_white", () -> new MetalDoorTallWindowWhiteItem());
    public static final RegistryObject<Item> METAL_DOOR_TALL_WINDOW_WHITE_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.METAL_DOOR_TALL_WINDOW_WHITE_BLOCK);
    public static final RegistryObject<Item> METAL_DOOR_TALL_WINDOW_YELLOW = REGISTRY.register("metal_door_tall_window_yellow", () -> new MetalDoorTallWindowYellowItem());
    public static final RegistryObject<Item> METAL_DOOR_TALL_WINDOW_YELLOW_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.METAL_DOOR_TALL_WINDOW_YELLOW_BLOCK);
    public static final RegistryObject<Item> METAL_DOOR_TALL_WINDOW_GREEN = REGISTRY.register("metal_door_tall_window_green", () -> new MetalDoorTallWindowGreenItem());
    public static final RegistryObject<Item> METAL_DOOR_TALL_WINDOW_GREEN_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.METAL_DOOR_TALL_WINDOW_GREEN_BLOCK);
    public static final RegistryObject<Item> METAL_DOOR_TALL_WINDOW_BROWN = REGISTRY.register("metal_door_tall_window_brown", () -> new MetalDoorTallWindowBrownItem());
    public static final RegistryObject<Item> METAL_DOOR_TALL_WINDOW_BROWN_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.METAL_DOOR_TALL_WINDOW_BROWN_BLOCK);
    public static final RegistryObject<Item> METAL_DOOR_TALL_WINDOW_BLACK = REGISTRY.register("metal_door_tall_window_black", () -> new MetalDoorTallWindowBlackItem());
    public static final RegistryObject<Item> METAL_DOOR_TALL_WINDOW_BLACK_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.METAL_DOOR_TALL_WINDOW_BLACK_BLOCK);
    public static final RegistryObject<Item> OLD_DOOR_TALL = REGISTRY.register("old_door_tall", () -> new OldDoorTallItem());
    public static final RegistryObject<Item> OLD_DOOR_TALL_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.OLD_DOOR_TALL_BLOCK);
    public static final RegistryObject<Item> UNDERWEAR = RojiuramodModItems.block(RojiuramodModBlocks.UNDERWEAR);
    public static final RegistryObject<Item> CLOTH_DRESS = RojiuramodModItems.block(RojiuramodModBlocks.CLOTH_DRESS);
    public static final RegistryObject<Item> SLIDING_DOOR_BROWN = REGISTRY.register("sliding_door_brown", () -> new SlidingDoorBrownItem());
    public static final RegistryObject<Item> SLIDING_DOOR_BROWN_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.SLIDING_DOOR_BROWN_BLOCK);
    public static final RegistryObject<Item> SLIDING_DOOR_LIGHT_BROWN = REGISTRY.register("sliding_door_light_brown", () -> new SlidingDoorLightBrownItem());
    public static final RegistryObject<Item> SLIDING_DOOR_LIGHT_BROWN_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.SLIDING_DOOR_LIGHT_BROWN_BLOCK);
    public static final RegistryObject<Item> SLIDING_DOOR_ORANGE_BROWN = REGISTRY.register("sliding_door_orange_brown", () -> new SlidingDoorOrangeBrownItem());
    public static final RegistryObject<Item> SLIDING_DOOR_ORANGE_BROWN_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.SLIDING_DOOR_ORANGE_BROWN_BLOCK);
    public static final RegistryObject<Item> SYOUJI_BROWN = REGISTRY.register("syouji_brown", () -> new SyoujiBrownItem());
    public static final RegistryObject<Item> SYOUJI_BROWN_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.SYOUJI_BROWN_BLOCK);
    public static final RegistryObject<Item> SYOUJI_LIGHT_BROWN = REGISTRY.register("syouji_light_brown", () -> new SyoujiLightBrownItem());
    public static final RegistryObject<Item> SYOUJI_LIGHT_BROWN_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.SYOUJI_LIGHT_BROWN_BLOCK);
    public static final RegistryObject<Item> SYOUJI_ORANGE_BROWN = REGISTRY.register("syouji_orange_brown", () -> new SyoujiOrangeBrownItem());
    public static final RegistryObject<Item> SYOUJI_ORANGE_BROWN_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.SYOUJI_ORANGE_BROWN_BLOCK);
    public static final RegistryObject<Item> SYOUJIYUKIMI_BROWN = REGISTRY.register("syoujiyukimi_brown", () -> new SyoujiyukimiBrownItem());
    public static final RegistryObject<Item> SYOUJIYUKIMI_BROWN_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.SYOUJIYUKIMI_BROWN_BLOCK);
    public static final RegistryObject<Item> SYOUJIYUKIMI_LIGHT_BROWN = REGISTRY.register("syoujiyukimi_light_brown", () -> new SyoujiyukimiLightBrownItem());
    public static final RegistryObject<Item> SYOUJIYUKIMI_LIGHT_BROWN_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.SYOUJIYUKIMI_LIGHT_BROWN_BLOCK);
    public static final RegistryObject<Item> SYOUJIYUKIMI_ORANGE_BROWN = REGISTRY.register("syoujiyukimi_orange_brown", () -> new SyoujiyukimiOrangeBrownItem());
    public static final RegistryObject<Item> SYOUJIYUKIMI_ORANGE_BROWN_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.SYOUJIYUKIMI_ORANGE_BROWN_BLOCK);
    public static final RegistryObject<Item> SLIDING_DOOR_TALL_BROWN = REGISTRY.register("sliding_door_tall_brown", () -> new SlidingDoorTallBrownItem());
    public static final RegistryObject<Item> SLIDING_DOOR_TALL_BROWN_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.SLIDING_DOOR_TALL_BROWN_BLOCK);
    public static final RegistryObject<Item> SLIDING_DOOR_TALL_LIGHT_BROWN = REGISTRY.register("sliding_door_tall_light_brown", () -> new SlidingDoorTallLightBrownItem());
    public static final RegistryObject<Item> SLIDING_DOOR_TALL_LIGHT_BROWN_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.SLIDING_DOOR_TALL_LIGHT_BROWN_BLOCK);
    public static final RegistryObject<Item> SLIDING_DOOR_TALL_ORANGE_BROWN = REGISTRY.register("sliding_door_tall_orange_brown", () -> new SlidingDoorTallOrangeBrownItem());
    public static final RegistryObject<Item> SLIDING_DOOR_TALL_ORANGE_BROWN_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.SLIDING_DOOR_TALL_ORANGE_BROWN_BLOCK);
    public static final RegistryObject<Item> SYOUJI_TALL_BROWN = REGISTRY.register("syouji_tall_brown", () -> new SyoujiTallBrownItem());
    public static final RegistryObject<Item> SYOUJI_TALL_BROWN_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.SYOUJI_TALL_BROWN_BLOCK);
    public static final RegistryObject<Item> SYOUJI_TALL_LIGHT_BROWN = REGISTRY.register("syouji_tall_light_brown", () -> new SyoujiTallLightBrownItem());
    public static final RegistryObject<Item> SYOUJI_TALL_LIGHT_BROWN_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.SYOUJI_TALL_LIGHT_BROWN_BLOCK);
    public static final RegistryObject<Item> SYOUJI_TALL_ORANGE_BROWN = REGISTRY.register("syouji_tall_orange_brown", () -> new SyoujiTallOrangeBrownItem());
    public static final RegistryObject<Item> SYOUJI_TALL_ORANGE_BROWN_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.SYOUJI_TALL_ORANGE_BROWN_BLOCK);
    public static final RegistryObject<Item> SYOUJIYUKIMI_TALL_BROWN = REGISTRY.register("syoujiyukimi_tall_brown", () -> new SyoujiyukimiTallBrownItem());
    public static final RegistryObject<Item> SYOUJIYUKIMI_TALL_BROWN_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.SYOUJIYUKIMI_TALL_BROWN_BLOCK);
    public static final RegistryObject<Item> SYOUJIYUKIMI_TALL_LIGHT_BROWN = REGISTRY.register("syoujiyukimi_tall_light_brown", () -> new SyoujiyukimiTallLightBrownItem());
    public static final RegistryObject<Item> SYOUJIYUKIMI_TALL_LIGHT_BROWN_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.SYOUJIYUKIMI_TALL_LIGHT_BROWN_BLOCK);
    public static final RegistryObject<Item> SYOUJIYUKIMI_TALL_ORANGE_BROWN = REGISTRY.register("syoujiyukimi_tall_orange_brown", () -> new SyoujiyukimiTallOrangeBrownItem());
    public static final RegistryObject<Item> SYOUJIYUKIMI_TALL_ORANGE_BROWN_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.SYOUJIYUKIMI_TALL_ORANGE_BROWN_BLOCK);
    public static final RegistryObject<Item> HUSUMA = REGISTRY.register("husuma", () -> new HusumaItem());
    public static final RegistryObject<Item> HUSUMA_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.HUSUMA_BLOCK);
    public static final RegistryObject<Item> HUSUMA_BLUE_LINE = REGISTRY.register("husuma_blue_line", () -> new HusumaBlueLineItem());
    public static final RegistryObject<Item> HUSUMA_BLUE_LINE_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.HUSUMA_BLUE_LINE_BLOCK);
    public static final RegistryObject<Item> HUSUMA_INK = REGISTRY.register("husuma_ink", () -> new HusumaInkItem());
    public static final RegistryObject<Item> HUSUMA_INK_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.HUSUMA_INK_BLOCK);
    public static final RegistryObject<Item> HUSUMA_SAKURA = REGISTRY.register("husuma_sakura", () -> new HusumaSakuraItem());
    public static final RegistryObject<Item> HUSUMA_SAKURA_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.HUSUMA_SAKURA_BLOCK);
    public static final RegistryObject<Item> HUSUMA_TALL = REGISTRY.register("husuma_tall", () -> new HusumaTallItem());
    public static final RegistryObject<Item> HUSUMA_TALL_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.HUSUMA_TALL_BLOCK);
    public static final RegistryObject<Item> HUSUMA_TALL_BLUE_LINE = REGISTRY.register("husuma_tall_blue_line", () -> new HusumaTallBlueLineItem());
    public static final RegistryObject<Item> HUSUMA_TALL_BLUE_LINE_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.HUSUMA_TALL_BLUE_LINE_BLOCK);
    public static final RegistryObject<Item> HUSUMA_TALL_INK = REGISTRY.register("husuma_tall_ink", () -> new HusumaTallInkItem());
    public static final RegistryObject<Item> HUSUMA_TALL_INK_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.HUSUMA_TALL_INK_BLOCK);
    public static final RegistryObject<Item> HUSUMA_TALL_SAKURA = REGISTRY.register("husuma_tall_sakura", () -> new HusumaTallSakuraItem());
    public static final RegistryObject<Item> HUSUMA_TALL_SAKURA_BLCOK = RojiuramodModItems.block(RojiuramodModBlocks.HUSUMA_TALL_SAKURA_BLCOK);
    public static final RegistryObject<Item> ALM_DOOR = REGISTRY.register("alm_door", () -> new AlmDoorItem());
    public static final RegistryObject<Item> ALM_DOOR_BLOCK = RojiuramodModItems.block(RojiuramodModBlocks.ALM_DOOR_BLOCK);
    public static final RegistryObject<Item> DUCT = RojiuramodModItems.block(RojiuramodModBlocks.DUCT);
    public static final RegistryObject<Item> OLD_PIPE = RojiuramodModItems.block(RojiuramodModBlocks.OLD_PIPE);
    public static final RegistryObject<Item> SITAMI_ITABARI_ORANGE_BROWN_SLAB = RojiuramodModItems.block(RojiuramodModBlocks.SITAMI_ITABARI_ORANGE_BROWN_SLAB);
    public static final RegistryObject<Item> SITAMI_ITABARI_LIGHT_BROWN_SLAB = RojiuramodModItems.block(RojiuramodModBlocks.SITAMI_ITABARI_LIGHT_BROWN_SLAB);
    public static final RegistryObject<Item> SITAMI_ITABARI_BROWN_SLAB = RojiuramodModItems.block(RojiuramodModBlocks.SITAMI_ITABARI_BROWN_SLAB);
    public static final RegistryObject<Item> SITAMI_ITABARI_DARK_BROWN_SLAB = RojiuramodModItems.block(RojiuramodModBlocks.SITAMI_ITABARI_DARK_BROWN_SLAB);
    public static final RegistryObject<Item> SITAMI_ITABARI_RED_SLAB = RojiuramodModItems.block(RojiuramodModBlocks.SITAMI_ITABARI_RED_SLAB);
    public static final RegistryObject<Item> DUCT_ITEM = REGISTRY.register("duct_item", () -> new DuctitemItem());
    public static final RegistryObject<Item> OLD_PIPE_ITEM = REGISTRY.register("old_pipe_item", () -> new OldPipeItemItem());
    public static final RegistryObject<Item> GLASS_ALM_WINDOW = RojiuramodModItems.block(RojiuramodModBlocks.GLASS_ALM_WINDOW);

    private static RegistryObject<Item> block(RegistryObject<Block> block) {
        return REGISTRY.register(block.getId().m_135815_(), () -> new BlockItem((Block)block.get(), new Item.Properties()));
    }
}

